(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aElement" (DB 0))) TRUTH))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sz0"))) ("aElement" (DB 0))))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sz1"))) ("aElement" (DB 0))))
("aElement" "xx")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("smndt" "xx"))) ("aElement" (DB 0))))
(AND ("aElement" "xx") ("aElement" "xy"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sdtpldt" "xx" "xy")))
  ("aElement" (DB 0))))
(AND ("aElement" "xx") ("aElement" "xy"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sdtasdt" "xx" "xy")))
  ("aElement" (DB 0))))
(AND ("aElement" "xx") ("aElement" "xy"))
("=" ("sdtpldt" "xx" "xy") ("sdtpldt" "xy" "xx"))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aElement" "xz"))
("=" ("sdtpldt" ("sdtpldt" "xx" "xy") "xz")
 ("sdtpldt" "xx" ("sdtpldt" "xy" "xz")))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aElement" "xz"))
("=" ("sdtpldt" "xx" ("sdtpldt" "xy" "xz"))
 ("sdtpldt" "xy" ("sdtpldt" "xx" "xz")))
("aElement" "xx")
(AND ("=" ("sdtpldt" "xx" ("sz0")) "xx") ("=" "xx" ("sdtpldt" ("sz0") "xx")))
("aElement" "xx")
(AND ("=" ("sdtpldt" "xx" ("smndt" "xx")) ("sz0"))
     ("=" ("sz0") ("sdtpldt" ("smndt" "xx") "xx")))
(AND ("aElement" "xx") ("aElement" "xy"))
("=" ("sdtasdt" "xx" "xy") ("sdtasdt" "xy" "xx"))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aElement" "xz"))
("=" ("sdtasdt" ("sdtasdt" "xx" "xy") "xz")
 ("sdtasdt" "xx" ("sdtasdt" "xy" "xz")))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aElement" "xz"))
("=" ("sdtasdt" "xx" ("sdtasdt" "xy" "xz"))
 ("sdtasdt" "xy" ("sdtasdt" "xx" "xz")))
("aElement" "xx")
(AND ("=" ("sdtasdt" "xx" ("sz1")) "xx") ("=" "xx" ("sdtasdt" ("sz1") "xx")))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aElement" "xz"))
("=" ("sdtasdt" "xx" ("sdtpldt" "xy" "xz"))
 ("sdtpldt" ("sdtasdt" "xx" "xy") ("sdtasdt" "xx" "xz")))
(AND (AND ("aElement" "xy") ("aElement" "xz")) ("aElement" "xx"))
("=" ("sdtasdt" ("sdtpldt" "xy" "xz") "xx")
 ("sdtpldt" ("sdtasdt" "xy" "xx") ("sdtasdt" "xz" "xx")))
("aElement" "xx")
(AND ("=" ("sdtasdt" ("smndt" ("sz1")) "xx") ("smndt" "xx"))
     ("=" ("smndt" "xx") ("sdtasdt" "xx" ("smndt" ("sz1")))))
("aElement" "xx")
(AND ("=" ("sdtasdt" "xx" ("sz0")) ("sz0"))
     ("=" ("sz0") ("sdtasdt" ("sz0") "xx")))
("=" ("sdtasdt" "xx" ("sz0")) ("sz0"))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xx" ("sz0"))
  ("sdtpldt" ("sdtasdt" "xx" ("sz0")) ("sdtasdt" "xx" ("sz0")))))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xx" ("sz0")) ("sdtasdt" "xx" ("sdtpldt" ("sz0") ("sz0")))))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xx" ("sdtpldt" ("sz0") ("sz0")))
  ("sdtpldt" ("sdtasdt" "xx" ("sz0")) ("sdtasdt" "xx" ("sz0")))))
("=" ("sdtasdt" ("sz0") "xx") ("sz0"))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" ("sz0") "xx")
  ("sdtpldt" ("sdtasdt" ("sz0") "xx") ("sdtasdt" ("sz0") "xx"))))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" ("sz0") "xx") ("sdtasdt" ("sdtpldt" ("sz0") ("sz0")) "xx")))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" ("sdtpldt" ("sz0") ("sz0")) "xx")
  ("sdtpldt" ("sdtasdt" ("sz0") "xx") ("sdtasdt" ("sz0") "xx"))))
(AND ("aElement" "xx") ("aElement" "xy"))
(IMPLIES (AND (NOT ("=" "xx" ("sz0"))) (NOT ("=" "xy" ("sz0"))))
 (NOT ("=" ("sdtasdt" "xx" "xy") ("sz0"))))
(NOT ("=" ("sz1") ("sz0")))
("aSet" "xX")
(FORALL (DB 0) (IMPLIES ("aElementOf" (DB 0) "xX") ("aElement" (DB 0))))
(AND ("aSet" "xX") ("aSet" "xY"))
(IMPLIES
 (AND
  (FORALL (DB 0)
   (IMPLIES ("aElementOf" (DB 0) "xX") ("aElementOf" (DB 0) "xY")))
  (FORALL (DB 0)
   (IMPLIES ("aElementOf" (DB 0) "xY") ("aElementOf" (DB 0) "xX"))))
 ("=" "xX" "xY"))
(AND ("aSet" "xX") ("aSet" "xY"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtplqtdt" "xX" "xY")))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElement" (DB 0))
         (IFF ("aElementOf" (DB 0) (DB 1))
          (EXISTS (DB 0)
           (AND ("aElementOf" (DB 0) "xX")
                (EXISTS (DB 0)
                 (AND ("aElementOf" (DB 0) "xY")
                      ("=" (DB 2) ("sdtpldt" (DB 1) (DB 0)))))))))))))
(AND ("aSet" "xX") ("aSet" "xY"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtasasdt" "xX" "xY")))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElement" (DB 0))
         (IFF ("aElementOf" (DB 0) ("sdtplqtdt" "xX" "xY"))
          (AND ("aElementOf" (DB 0) "xX") ("aElementOf" (DB 0) "xY"))))))))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aIdeal" (DB 0)))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElementOf" (DB 0) (DB 1))
         (AND
          (FORALL (DB 0)
           (IMPLIES ("aElementOf" (DB 0) (DB 2))
            ("aElementOf" ("sdtpldt" (DB 1) (DB 0)) (DB 2))))
          (FORALL (DB 0)
           (IMPLIES ("aElement" (DB 0))
            ("aElementOf" ("sdtasdt" (DB 0) (DB 1)) (DB 2))))))))))
(AND ("aIdeal" "xI") ("aIdeal" "xJ"))
("aIdeal" ("sdtplqtdt" "xI" "xJ"))
("aElementOf" "xx" ("sdtplqtdt" "xI" "xJ"))
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) ("sdtplqtdt" "xI" "xJ"))
  ("aElementOf" ("sdtpldt" "xx" (DB 0)) ("sdtplqtdt" "xI" "xJ"))))
("aElementOf" "xy" ("sdtplqtdt" "xI" "xJ"))
(AND ("aElementOf" "xk" "xI")
     (AND ("aElementOf" "xl" "xJ") ("=" "xx" ("sdtpldt" "xk" "xl"))))
(AND ("aElementOf" "xm" "xI")
     (AND ("aElementOf" "xn" "xJ") ("=" "xy" ("sdtpldt" "xm" "xn"))))
(AND ("aElementOf" ("sdtpldt" "xk" "xm") "xI")
     ("aElementOf" ("sdtpldt" "xl" "xn") "xJ"))
(EQUALITYCHAIN TAG
 ("=" ("sdtpldt" "xx" "xy")
  ("sdtpldt" ("sdtpldt" "xk" "xm") ("sdtpldt" "xl" "xn"))))
(EQUALITYCHAIN TAG
 ("=" ("sdtpldt" "xx" "xy")
  ("sdtpldt" ("sdtpldt" "xk" "xm") ("sdtpldt" "xl" "xn"))))
("#TH#")
(FORALL (DB 0)
 (IMPLIES ("aElement" (DB 0))
  ("aElementOf" ("sdtasdt" (DB 0) "xx") ("sdtplqtdt" "xI" "xJ"))))
("aElement" "xz")
(AND ("aElementOf" "xk" "xI")
     (AND ("aElementOf" "xl" "xJ") ("=" "xx" ("sdtpldt" "xk" "xl"))))
(AND ("aElementOf" ("sdtasdt" "xz" "xk") "xI")
     ("aElementOf" ("sdtasdt" "xz" "xl") "xJ"))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xz" "xx")
  ("sdtpldt" ("sdtasdt" "xz" "xk") ("sdtasdt" "xz" "xl"))))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xz" "xx")
  ("sdtpldt" ("sdtasdt" "xz" "xk") ("sdtasdt" "xz" "xl"))))
("#TH#")
(AND ("aIdeal" "xI") ("aIdeal" "xJ"))
("aIdeal" ("sdtasasdt" "xI" "xJ"))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aIdeal" "xI"))
(IFF (HEADTERM TAG ("sdteqdtlpzmzozddtrp" "xx" "xy" "xI"))
 ("aElementOf" ("sdtpldt" "xx" ("smndt" "xy")) "xI"))
(AND ("aIdeal" "xI") ("aIdeal" "xJ"))
(FORALL (DB 0)
 (IMPLIES ("aElement" (DB 0)) ("aElementOf" (DB 0) ("sdtplqtdt" "xI" "xJ"))))
(AND ("aElement" "xx") ("aElement" "xy"))
(EXISTS (DB 0)
 (AND ("aElement" (DB 0))
      (AND ("sdteqdtlpzmzozddtrp" (DB 0) "xx" "xI")
           ("sdteqdtlpzmzozddtrp" (DB 0) "xy" "xJ"))))
(AND ("aElementOf" "xa" "xI")
     (AND ("aElementOf" "xb" "xJ") ("=" ("sdtpldt" "xa" "xb") ("sz1"))))
("=" "xw" ("sdtpldt" ("sdtasdt" "xy" "xa") ("sdtasdt" "xx" "xb")))
(AND ("sdteqdtlpzmzozddtrp" "xw" "xx" "xI")
     ("sdteqdtlpzmzozddtrp" "xw" "xy" "xJ"))
("aElementOf" ("sdtpldt" "xw" ("smndt" "xx")) "xI")
("=" ("sdtpldt" "xw" ("smndt" "xx"))
 ("sdtpldt" ("sdtasdt" "xy" "xa")
  ("sdtpldt" ("sdtasdt" "xx" "xb") ("smndt" "xx"))))
("aElementOf" ("sdtasdt" "xx" ("sdtpldt" "xb" ("smndt" ("sz1")))) "xI")
("aElementOf" ("sdtpldt" "xw" ("smndt" "xy")) "xJ")
("=" ("sdtpldt" "xw" ("smndt" "xy"))
 ("sdtpldt" ("sdtasdt" "xx" "xb")
  ("sdtpldt" ("sdtasdt" "xy" "xa") ("smndt" "xy"))))
("aElementOf" ("sdtasdt" "xy" ("sdtpldt" "xa" ("smndt" ("sz1")))) "xJ")
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aNaturalNumber" (DB 0))) TRUTH))
(AND ("aElement" "xx") (NOT ("=" "xx" ("sz0"))))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sbrdtbr" "xx")))
  ("aNaturalNumber" (DB 0))))
(AND (AND ("aElement" "xx") ("aElement" "xy")) (NOT ("=" "xy" ("sz0"))))
(EXISTS (DB 0)
 (EXISTS (DB 0)
  (AND (AND ("aElement" (DB 1)) ("aElement" (DB 0)))
       (AND ("=" "xx" ("sdtpldt" ("sdtasdt" (DB 1) "xy") (DB 0)))
            (IMPLIES (NOT ("=" (DB 0) ("sz0")))
             ("iLess" ("sbrdtbr" (DB 0)) ("sbrdtbr" "xy")))))))
(AND ("aElement" "xx") ("aElement" "xy"))
(IFF (HEADTERM TAG ("doDivides" "xx" "xy"))
 (EXISTS (DB 0) (AND ("aElement" (DB 0)) ("=" ("sdtasdt" "xx" (DB 0)) "xy"))))
("aElement" "xx")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aDivisorOf" (DB 0) "xx"))
  (AND ("aElement" (DB 0)) ("doDivides" (DB 0) "xx"))))
(AND ("aElement" "xx") ("aElement" "xy"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aGcdOfAnd" (DB 0) "xx" "xy"))
  (AND (AND ("aDivisorOf" (DB 0) "xx") ("aDivisorOf" (DB 0) "xy"))
       (FORALL (DB 0)
        (IMPLIES (AND ("aDivisorOf" (DB 0) "xx") ("aDivisorOf" (DB 0) "xy"))
         ("doDivides" (DB 0) (DB 1)))))))
(AND ("aElement" "xx") ("aElement" "xy"))
(IFF (HEADTERM TAG ("misRelativelyPrime" "xx" "xy"))
 ("aGcdOfAnd" ("sz1") "xx" "xy"))
("aElement" "xc")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("slsdtgt" "xc")))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElement" (DB 0))
         (IFF ("aElementOf" (DB 0) (DB 1))
          (EXISTS (DB 0)
           (AND ("aElement" (DB 0)) ("=" (DB 1) ("sdtasdt" "xc" (DB 0)))))))))))
("aElement" "xc")
("aIdeal" ("slsdtgt" "xc"))
("aElementOf" "xx" ("slsdtgt" "xc"))
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) ("slsdtgt" "xc"))
  ("aElementOf" ("sdtpldt" "xx" (DB 0)) ("slsdtgt" "xc"))))
("aElementOf" "xy" ("slsdtgt" "xc"))
(AND ("aElement" "xu") ("=" ("sdtasdt" "xc" "xu") "xx"))
(AND ("aElement" "xv") ("=" ("sdtasdt" "xc" "xv") "xy"))
(EQUALITYCHAIN TAG
 ("=" ("sdtpldt" "xx" "xy") ("sdtasdt" "xc" ("sdtpldt" "xu" "xv"))))
(EQUALITYCHAIN TAG
 ("=" ("sdtpldt" "xx" "xy") ("sdtasdt" "xc" ("sdtpldt" "xu" "xv"))))
("#TH#")
(FORALL (DB 0)
 (IMPLIES ("aElement" (DB 0))
  ("aElementOf" ("sdtasdt" (DB 0) "xx") ("slsdtgt" "xc"))))
("aElement" "xz")
(AND ("aElement" "xu") ("=" ("sdtasdt" "xc" "xu") "xx"))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xz" "xx") ("sdtasdt" "xc" ("sdtasdt" "xu" "xz"))))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xz" "xx") ("sdtasdt" "xc" ("sdtasdt" "xu" "xz"))))
("#TH#")
(AND ("aElement" "xa") ("aElement" "xb"))
(OR (NOT ("=" "xa" ("sz0"))) (NOT ("=" "xb" ("sz0"))))
("aGcdOfAnd" "xc" "xa" "xb")
("aElementOf" "xc" ("sdtplqtdt" ("slsdtgt" "xa") ("slsdtgt" "xb")))
(AND ("aIdeal" "xI") ("=" "xI" ("sdtplqtdt" ("slsdtgt" "xa") ("slsdtgt" "xb"))))
(AND
 (AND ("aElementOf" ("sz0") ("slsdtgt" "xa"))
      ("aElementOf" "xa" ("slsdtgt" "xa")))
 (AND ("aElementOf" ("sz0") ("slsdtgt" "xb"))
      ("aElementOf" "xb" ("slsdtgt" "xb"))))
(EXISTS (DB 0)
 (AND ("aElementOf" (DB 0) ("sdtplqtdt" ("slsdtgt" "xa") ("slsdtgt" "xb")))
      (NOT ("=" (DB 0) ("sz0")))))
(AND ("aElementOf" "xa" ("sdtplqtdt" ("slsdtgt" "xa") ("slsdtgt" "xb")))
     ("aElementOf" "xb" ("sdtplqtdt" ("slsdtgt" "xa") ("slsdtgt" "xb"))))
(AND ("aElementOf" "xu" "xI")
     (AND (NOT ("=" "xu" ("sz0")))
          (FORALL (DB 0)
           (IMPLIES (AND ("aElementOf" (DB 0) "xI") (NOT ("=" (DB 0) ("sz0"))))
            (NOT ("iLess" ("sbrdtbr" (DB 0)) ("sbrdtbr" "xu")))))))
(NOT ("#TH#"))
(FORALL (DB 0)
 (IMPLIES (AND ("aElementOf" (DB 0) "xI") (NOT ("=" (DB 0) ("sz0"))))
  (IMPLIES
   (INDUCTIONHYPOTHESIS TAG
    (FORALL (DB 0)
     (IMPLIES (AND ("aElementOf" (DB 0) "xI") (NOT ("=" (DB 0) ("sz0"))))
      (IMPLIES ("iLess" ("sbrdtbr" (DB 0)) ("sbrdtbr" (DB 1)))
       (EXISTS (DB 0)
        (AND ("aElementOf" (DB 0) "xI")
             (AND (NOT ("=" (DB 0) ("sz0")))
                  (FORALL (DB 0)
                   (IMPLIES
                    (AND ("aElementOf" (DB 0) "xI") (NOT ("=" (DB 0) ("sz0"))))
                    (NOT
                     ("iLess" ("sbrdtbr" (DB 0)) ("sbrdtbr" (DB 1)))))))))))))
   (EXISTS (DB 0)
    (AND ("aElementOf" (DB 0) "xI")
         (AND (NOT ("=" (DB 0) ("sz0")))
              (FORALL (DB 0)
               (IMPLIES
                (AND ("aElementOf" (DB 0) "xI") (NOT ("=" (DB 0) ("sz0"))))
                (NOT ("iLess" ("sbrdtbr" (DB 0)) ("sbrdtbr" (DB 1))))))))))))
(AND ("aDivisorOf" "xu" "xa") ("aDivisorOf" "xu" "xb"))
(NOT ("#TH#"))
(EXISTS (DB 0)
 (EXISTS (DB 0)
  (AND (AND ("aElement" (DB 1)) ("aElement" (DB 0)))
       ("=" "xu" ("sdtpldt" ("sdtasdt" "xa" (DB 1)) ("sdtasdt" "xb" (DB 0)))))))
(AND ("aElementOf" "xk" ("slsdtgt" "xa"))
     (AND ("aElementOf" "xl" ("slsdtgt" "xb"))
          ("=" "xu" ("sdtpldt" "xk" "xl"))))
(AND (AND ("aElement" "xx") ("aElement" "xy"))
     (AND ("=" "xk" ("sdtasdt" "xa" "xx")) ("=" "xl" ("sdtasdt" "xb" "xy"))))
("#TH#")
(IMPLIES (CASEHYPOTHESIS TAG (NOT ("doDivides" "xu" "xa"))) ("#TH#"))
(AND (AND ("aElement" "xq") ("aElement" "xr"))
     (AND ("=" "xa" ("sdtpldt" ("sdtasdt" "xq" "xu") "xr"))
          (OR ("=" "xr" ("sz0")) ("iLess" ("sbrdtbr" "xr") ("sbrdtbr" "xu")))))
(NOT ("=" "xr" ("sz0")))
("aElementOf" ("smndt" ("sdtasdt" "xq" "xu")) "xI")
("aElementOf" "xa" "xI")
("=" "xr" ("sdtpldt" ("smndt" ("sdtasdt" "xq" "xu")) "xa"))
("aElementOf" "xr" "xI")
(IMPLIES (CASEHYPOTHESIS TAG (NOT ("doDivides" "xu" "xb"))) ("#TH#"))
(AND (AND ("aElement" "xq") ("aElement" "xr"))
     (AND ("=" "xb" ("sdtpldt" ("sdtasdt" "xq" "xu") "xr"))
          (OR ("=" "xr" ("sz0")) ("iLess" ("sbrdtbr" "xr") ("sbrdtbr" "xu")))))
(NOT ("=" "xr" ("sz0")))
("aElementOf" ("smndt" ("sdtasdt" "xq" "xu")) "xI")
("aElementOf" "xb" "xI")
("=" "xr" ("sdtpldt" ("smndt" ("sdtasdt" "xq" "xu")) "xb"))
("aElementOf" "xr" "xI")
("doDivides" "xu" "xc")
("#TH#")
(AND ("aElement" "xz") ("=" "xc" ("sdtasdt" "xz" "xu")))
("aElementOf" "xc" "xI")
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aElement" (DB 0))) TRUTH))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sz0"))) ("aElement" (DB 0))))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sz1"))) ("aElement" (DB 0))))
("aElement" "xx")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("smndt" "xx"))) ("aElement" (DB 0))))
(AND ("aElement" "xx") ("aElement" "xy"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sdtpldt" "xx" "xy")))
  ("aElement" (DB 0))))
(AND ("aElement" "xx") ("aElement" "xy"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sdtasdt" "xx" "xy")))
  ("aElement" (DB 0))))
(AND ("aElement" "xx") ("aElement" "xy"))
("=" ("sdtpldt" "xx" "xy") ("sdtpldt" "xy" "xx"))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aElement" "xz"))
("=" ("sdtpldt" ("sdtpldt" "xx" "xy") "xz")
 ("sdtpldt" "xx" ("sdtpldt" "xy" "xz")))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aElement" "xz"))
("=" ("sdtpldt" "xx" ("sdtpldt" "xy" "xz"))
 ("sdtpldt" "xy" ("sdtpldt" "xx" "xz")))
("aElement" "xx")
(AND ("=" ("sdtpldt" "xx" ("sz0")) "xx") ("=" "xx" ("sdtpldt" ("sz0") "xx")))
("aElement" "xx")
(AND ("=" ("sdtpldt" "xx" ("smndt" "xx")) ("sz0"))
     ("=" ("sz0") ("sdtpldt" ("smndt" "xx") "xx")))
(AND ("aElement" "xx") ("aElement" "xy"))
("=" ("sdtasdt" "xx" "xy") ("sdtasdt" "xy" "xx"))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aElement" "xz"))
("=" ("sdtasdt" ("sdtasdt" "xx" "xy") "xz")
 ("sdtasdt" "xx" ("sdtasdt" "xy" "xz")))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aElement" "xz"))
("=" ("sdtasdt" "xx" ("sdtasdt" "xy" "xz"))
 ("sdtasdt" "xy" ("sdtasdt" "xx" "xz")))
("aElement" "xx")
(AND ("=" ("sdtasdt" "xx" ("sz1")) "xx") ("=" "xx" ("sdtasdt" ("sz1") "xx")))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aElement" "xz"))
("=" ("sdtasdt" "xx" ("sdtpldt" "xy" "xz"))
 ("sdtpldt" ("sdtasdt" "xx" "xy") ("sdtasdt" "xx" "xz")))
(AND (AND ("aElement" "xy") ("aElement" "xz")) ("aElement" "xx"))
("=" ("sdtasdt" ("sdtpldt" "xy" "xz") "xx")
 ("sdtpldt" ("sdtasdt" "xy" "xx") ("sdtasdt" "xz" "xx")))
("aElement" "xx")
(AND ("=" ("sdtasdt" ("smndt" ("sz1")) "xx") ("smndt" "xx"))
     ("=" ("smndt" "xx") ("sdtasdt" "xx" ("smndt" ("sz1")))))
("aElement" "xx")
(AND ("=" ("sdtasdt" "xx" ("sz0")) ("sz0"))
     ("=" ("sz0") ("sdtasdt" ("sz0") "xx")))
("=" ("sdtasdt" "xx" ("sz0")) ("sz0"))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xx" ("sz0"))
  ("sdtpldt" ("sdtasdt" "xx" ("sz0")) ("sdtasdt" "xx" ("sz0")))))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xx" ("sz0")) ("sdtasdt" "xx" ("sdtpldt" ("sz0") ("sz0")))))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xx" ("sdtpldt" ("sz0") ("sz0")))
  ("sdtpldt" ("sdtasdt" "xx" ("sz0")) ("sdtasdt" "xx" ("sz0")))))
("=" ("sdtasdt" ("sz0") "xx") ("sz0"))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" ("sz0") "xx")
  ("sdtpldt" ("sdtasdt" ("sz0") "xx") ("sdtasdt" ("sz0") "xx"))))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" ("sz0") "xx") ("sdtasdt" ("sdtpldt" ("sz0") ("sz0")) "xx")))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" ("sdtpldt" ("sz0") ("sz0")) "xx")
  ("sdtpldt" ("sdtasdt" ("sz0") "xx") ("sdtasdt" ("sz0") "xx"))))
(AND ("aElement" "xx") ("aElement" "xy"))
(IMPLIES (AND (NOT ("=" "xx" ("sz0"))) (NOT ("=" "xy" ("sz0"))))
 (NOT ("=" ("sdtasdt" "xx" "xy") ("sz0"))))
(NOT ("=" ("sz1") ("sz0")))
("aSet" "xX")
(FORALL (DB 0) (IMPLIES ("aElementOf" (DB 0) "xX") ("aElement" (DB 0))))
(AND ("aSet" "xX") ("aSet" "xY"))
(IMPLIES
 (AND
  (FORALL (DB 0)
   (IMPLIES ("aElementOf" (DB 0) "xX") ("aElementOf" (DB 0) "xY")))
  (FORALL (DB 0)
   (IMPLIES ("aElementOf" (DB 0) "xY") ("aElementOf" (DB 0) "xX"))))
 ("=" "xX" "xY"))
(AND ("aSet" "xX") ("aSet" "xY"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtplqtdt" "xX" "xY")))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElement" (DB 0))
         (IFF ("aElementOf" (DB 0) (DB 1))
          (EXISTS (DB 0)
           (AND ("aElementOf" (DB 0) "xX")
                (EXISTS (DB 0)
                 (AND ("aElementOf" (DB 0) "xY")
                      ("=" (DB 2) ("sdtpldt" (DB 1) (DB 0)))))))))))))
(AND ("aSet" "xX") ("aSet" "xY"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtasasdt" "xX" "xY")))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElement" (DB 0))
         (IFF ("aElementOf" (DB 0) ("sdtplqtdt" "xX" "xY"))
          (AND ("aElementOf" (DB 0) "xX") ("aElementOf" (DB 0) "xY"))))))))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aIdeal" (DB 0)))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElementOf" (DB 0) (DB 1))
         (AND
          (FORALL (DB 0)
           (IMPLIES ("aElementOf" (DB 0) (DB 2))
            ("aElementOf" ("sdtpldt" (DB 1) (DB 0)) (DB 2))))
          (FORALL (DB 0)
           (IMPLIES ("aElement" (DB 0))
            ("aElementOf" ("sdtasdt" (DB 0) (DB 1)) (DB 2))))))))))
(AND ("aIdeal" "xI") ("aIdeal" "xJ"))
("aIdeal" ("sdtplqtdt" "xI" "xJ"))
("aElementOf" "xx" ("sdtplqtdt" "xI" "xJ"))
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) ("sdtplqtdt" "xI" "xJ"))
  ("aElementOf" ("sdtpldt" "xx" (DB 0)) ("sdtplqtdt" "xI" "xJ"))))
("aElementOf" "xy" ("sdtplqtdt" "xI" "xJ"))
(AND ("aElementOf" "xk" "xI")
     (AND ("aElementOf" "xl" "xJ") ("=" "xx" ("sdtpldt" "xk" "xl"))))
(AND ("aElementOf" "xm" "xI")
     (AND ("aElementOf" "xn" "xJ") ("=" "xy" ("sdtpldt" "xm" "xn"))))
(AND ("aElementOf" ("sdtpldt" "xk" "xm") "xI")
     ("aElementOf" ("sdtpldt" "xl" "xn") "xJ"))
(EQUALITYCHAIN TAG
 ("=" ("sdtpldt" "xx" "xy")
  ("sdtpldt" ("sdtpldt" "xk" "xm") ("sdtpldt" "xl" "xn"))))
(EQUALITYCHAIN TAG
 ("=" ("sdtpldt" "xx" "xy")
  ("sdtpldt" ("sdtpldt" "xk" "xm") ("sdtpldt" "xl" "xn"))))
("#TH#")
(FORALL (DB 0)
 (IMPLIES ("aElement" (DB 0))
  ("aElementOf" ("sdtasdt" (DB 0) "xx") ("sdtplqtdt" "xI" "xJ"))))
("aElement" "xz")
(AND ("aElementOf" "xk" "xI")
     (AND ("aElementOf" "xl" "xJ") ("=" "xx" ("sdtpldt" "xk" "xl"))))
(AND ("aElementOf" ("sdtasdt" "xz" "xk") "xI")
     ("aElementOf" ("sdtasdt" "xz" "xl") "xJ"))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xz" "xx")
  ("sdtpldt" ("sdtasdt" "xz" "xk") ("sdtasdt" "xz" "xl"))))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xz" "xx")
  ("sdtpldt" ("sdtasdt" "xz" "xk") ("sdtasdt" "xz" "xl"))))
("#TH#")
(AND ("aIdeal" "xI") ("aIdeal" "xJ"))
("aIdeal" ("sdtasasdt" "xI" "xJ"))
(AND (AND ("aElement" "xx") ("aElement" "xy")) ("aIdeal" "xI"))
(IFF (HEADTERM TAG ("sdteqdtlpzmzozddtrp" "xx" "xy" "xI"))
 ("aElementOf" ("sdtpldt" "xx" ("smndt" "xy")) "xI"))
(AND ("aIdeal" "xI") ("aIdeal" "xJ"))
(FORALL (DB 0)
 (IMPLIES ("aElement" (DB 0)) ("aElementOf" (DB 0) ("sdtplqtdt" "xI" "xJ"))))
(AND ("aElement" "xx") ("aElement" "xy"))
(EXISTS (DB 0)
 (AND ("aElement" (DB 0))
      (AND ("sdteqdtlpzmzozddtrp" (DB 0) "xx" "xI")
           ("sdteqdtlpzmzozddtrp" (DB 0) "xy" "xJ"))))
(AND ("aElementOf" "xa" "xI")
     (AND ("aElementOf" "xb" "xJ") ("=" ("sdtpldt" "xa" "xb") ("sz1"))))
("=" "xw" ("sdtpldt" ("sdtasdt" "xy" "xa") ("sdtasdt" "xx" "xb")))
(AND ("sdteqdtlpzmzozddtrp" "xw" "xx" "xI")
     ("sdteqdtlpzmzozddtrp" "xw" "xy" "xJ"))
("aElementOf" ("sdtpldt" "xw" ("smndt" "xx")) "xI")
("=" ("sdtpldt" "xw" ("smndt" "xx"))
 ("sdtpldt" ("sdtasdt" "xy" "xa")
  ("sdtpldt" ("sdtasdt" "xx" "xb") ("smndt" "xx"))))
("aElementOf" ("sdtasdt" "xx" ("sdtpldt" "xb" ("smndt" ("sz1")))) "xI")
("aElementOf" ("sdtpldt" "xw" ("smndt" "xy")) "xJ")
("=" ("sdtpldt" "xw" ("smndt" "xy"))
 ("sdtpldt" ("sdtasdt" "xx" "xb")
  ("sdtpldt" ("sdtasdt" "xy" "xa") ("smndt" "xy"))))
("aElementOf" ("sdtasdt" "xy" ("sdtpldt" "xa" ("smndt" ("sz1")))) "xJ")
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aNaturalNumber" (DB 0))) TRUTH))
(AND ("aElement" "xx") (NOT ("=" "xx" ("sz0"))))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sbrdtbr" "xx")))
  ("aNaturalNumber" (DB 0))))
(AND (AND ("aElement" "xx") ("aElement" "xy")) (NOT ("=" "xy" ("sz0"))))
(EXISTS (DB 0)
 (EXISTS (DB 0)
  (AND (AND ("aElement" (DB 1)) ("aElement" (DB 0)))
       (AND ("=" "xx" ("sdtpldt" ("sdtasdt" (DB 1) "xy") (DB 0)))
            (IMPLIES (NOT ("=" (DB 0) ("sz0")))
             ("iLess" ("sbrdtbr" (DB 0)) ("sbrdtbr" "xy")))))))
(AND ("aElement" "xx") ("aElement" "xy"))
(IFF (HEADTERM TAG ("doDivides" "xx" "xy"))
 (EXISTS (DB 0) (AND ("aElement" (DB 0)) ("=" ("sdtasdt" "xx" (DB 0)) "xy"))))
("aElement" "xx")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aDivisorOf" (DB 0) "xx"))
  (AND ("aElement" (DB 0)) ("doDivides" (DB 0) "xx"))))
(AND ("aElement" "xx") ("aElement" "xy"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aGcdOfAnd" (DB 0) "xx" "xy"))
  (AND (AND ("aDivisorOf" (DB 0) "xx") ("aDivisorOf" (DB 0) "xy"))
       (FORALL (DB 0)
        (IMPLIES (AND ("aDivisorOf" (DB 0) "xx") ("aDivisorOf" (DB 0) "xy"))
         ("doDivides" (DB 0) (DB 1)))))))
(AND ("aElement" "xx") ("aElement" "xy"))
(IFF (HEADTERM TAG ("misRelativelyPrime" "xx" "xy"))
 ("aGcdOfAnd" ("sz1") "xx" "xy"))
("aElement" "xc")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("slsdtgt" "xc")))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElement" (DB 0))
         (IFF ("aElementOf" (DB 0) (DB 1))
          (EXISTS (DB 0)
           (AND ("aElement" (DB 0)) ("=" (DB 1) ("sdtasdt" "xc" (DB 0)))))))))))
("aElement" "xc")
("aIdeal" ("slsdtgt" "xc"))
("aElementOf" "xx" ("slsdtgt" "xc"))
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) ("slsdtgt" "xc"))
  ("aElementOf" ("sdtpldt" "xx" (DB 0)) ("slsdtgt" "xc"))))
("aElementOf" "xy" ("slsdtgt" "xc"))
(AND ("aElement" "xu") ("=" ("sdtasdt" "xc" "xu") "xx"))
(AND ("aElement" "xv") ("=" ("sdtasdt" "xc" "xv") "xy"))
(EQUALITYCHAIN TAG
 ("=" ("sdtpldt" "xx" "xy") ("sdtasdt" "xc" ("sdtpldt" "xu" "xv"))))
(EQUALITYCHAIN TAG
 ("=" ("sdtpldt" "xx" "xy") ("sdtasdt" "xc" ("sdtpldt" "xu" "xv"))))
("#TH#")
(FORALL (DB 0)
 (IMPLIES ("aElement" (DB 0))
  ("aElementOf" ("sdtasdt" (DB 0) "xx") ("slsdtgt" "xc"))))
("aElement" "xz")
(AND ("aElement" "xu") ("=" ("sdtasdt" "xc" "xu") "xx"))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xz" "xx") ("sdtasdt" "xc" ("sdtasdt" "xu" "xz"))))
(EQUALITYCHAIN TAG
 ("=" ("sdtasdt" "xz" "xx") ("sdtasdt" "xc" ("sdtasdt" "xu" "xz"))))
("#TH#")
(AND ("aElement" "xa") ("aElement" "xb"))
(OR (NOT ("=" "xa" ("sz0"))) (NOT ("=" "xb" ("sz0"))))
("aGcdOfAnd" "xc" "xa" "xb")
("aElementOf" "xc" ("sdtplqtdt" ("slsdtgt" "xa") ("slsdtgt" "xb")))
(AND ("aIdeal" "xI") ("=" "xI" ("sdtplqtdt" ("slsdtgt" "xa") ("slsdtgt" "xb"))))
(AND
 (AND ("aElementOf" ("sz0") ("slsdtgt" "xa"))
      ("aElementOf" "xa" ("slsdtgt" "xa")))
 (AND ("aElementOf" ("sz0") ("slsdtgt" "xb"))
      ("aElementOf" "xb" ("slsdtgt" "xb"))))
(EXISTS (DB 0)
 (AND ("aElementOf" (DB 0) ("sdtplqtdt" ("slsdtgt" "xa") ("slsdtgt" "xb")))
      (NOT ("=" (DB 0) ("sz0")))))
(AND ("aElementOf" "xa" ("sdtplqtdt" ("slsdtgt" "xa") ("slsdtgt" "xb")))
     ("aElementOf" "xb" ("sdtplqtdt" ("slsdtgt" "xa") ("slsdtgt" "xb"))))
(AND ("aElementOf" "xu" "xI")
     (AND (NOT ("=" "xu" ("sz0")))
          (FORALL (DB 0)
           (IMPLIES (AND ("aElementOf" (DB 0) "xI") (NOT ("=" (DB 0) ("sz0"))))
            (NOT ("iLess" ("sbrdtbr" (DB 0)) ("sbrdtbr" "xu")))))))
(NOT ("#TH#"))
(FORALL (DB 0)
 (IMPLIES (AND ("aElementOf" (DB 0) "xI") (NOT ("=" (DB 0) ("sz0"))))
  (IMPLIES
   (INDUCTIONHYPOTHESIS TAG
    (FORALL (DB 0)
     (IMPLIES (AND ("aElementOf" (DB 0) "xI") (NOT ("=" (DB 0) ("sz0"))))
      (IMPLIES ("iLess" ("sbrdtbr" (DB 0)) ("sbrdtbr" (DB 1)))
       (EXISTS (DB 0)
        (AND ("aElementOf" (DB 0) "xI")
             (AND (NOT ("=" (DB 0) ("sz0")))
                  (FORALL (DB 0)
                   (IMPLIES
                    (AND ("aElementOf" (DB 0) "xI") (NOT ("=" (DB 0) ("sz0"))))
                    (NOT
                     ("iLess" ("sbrdtbr" (DB 0)) ("sbrdtbr" (DB 1)))))))))))))
   (EXISTS (DB 0)
    (AND ("aElementOf" (DB 0) "xI")
         (AND (NOT ("=" (DB 0) ("sz0")))
              (FORALL (DB 0)
               (IMPLIES
                (AND ("aElementOf" (DB 0) "xI") (NOT ("=" (DB 0) ("sz0"))))
                (NOT ("iLess" ("sbrdtbr" (DB 0)) ("sbrdtbr" (DB 1))))))))))))
(AND ("aDivisorOf" "xu" "xa") ("aDivisorOf" "xu" "xb"))
(NOT ("#TH#"))
(EXISTS (DB 0)
 (EXISTS (DB 0)
  (AND (AND ("aElement" (DB 1)) ("aElement" (DB 0)))
       ("=" "xu" ("sdtpldt" ("sdtasdt" "xa" (DB 1)) ("sdtasdt" "xb" (DB 0)))))))
(AND ("aElementOf" "xk" ("slsdtgt" "xa"))
     (AND ("aElementOf" "xl" ("slsdtgt" "xb"))
          ("=" "xu" ("sdtpldt" "xk" "xl"))))
(AND (AND ("aElement" "xx") ("aElement" "xy"))
     (AND ("=" "xk" ("sdtasdt" "xa" "xx")) ("=" "xl" ("sdtasdt" "xb" "xy"))))
("#TH#")
(IMPLIES (CASEHYPOTHESIS TAG (NOT ("doDivides" "xu" "xa"))) ("#TH#"))
(AND (AND ("aElement" "xq") ("aElement" "xr"))
     (AND ("=" "xa" ("sdtpldt" ("sdtasdt" "xq" "xu") "xr"))
          (OR ("=" "xr" ("sz0")) ("iLess" ("sbrdtbr" "xr") ("sbrdtbr" "xu")))))
(NOT ("=" "xr" ("sz0")))
("aElementOf" ("smndt" ("sdtasdt" "xq" "xu")) "xI")
("aElementOf" "xa" "xI")
("=" "xr" ("sdtpldt" ("smndt" ("sdtasdt" "xq" "xu")) "xa"))
("aElementOf" "xr" "xI")
(IMPLIES (CASEHYPOTHESIS TAG (NOT ("doDivides" "xu" "xb"))) ("#TH#"))
(AND (AND ("aElement" "xq") ("aElement" "xr"))
     (AND ("=" "xb" ("sdtpldt" ("sdtasdt" "xq" "xu") "xr"))
          (OR ("=" "xr" ("sz0")) ("iLess" ("sbrdtbr" "xr") ("sbrdtbr" "xu")))))
(NOT ("=" "xr" ("sz0")))
("aElementOf" ("smndt" ("sdtasdt" "xq" "xu")) "xI")
("aElementOf" "xb" "xI")
("=" "xr" ("sdtpldt" ("smndt" ("sdtasdt" "xq" "xu")) "xb"))
("aElementOf" "xr" "xI")
("doDivides" "xu" "xc")
("#TH#")
(AND ("aElement" "xz") ("=" "xc" ("sdtasdt" "xz" "xu")))
("aElementOf" "xc" "xI")
