("aSet" "xM")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aSubsetOf" (DB 0) "xM"))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElementOf" (DB 0) (DB 1)) ("aElementOf" (DB 0) "xM"))))))
(AND ("aSet" "xM") ("aSet" "xN"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtbsdt" "xM" "xN")))
  (AND ("aSet" (DB 0))
       ("=" (DB 0)
        (LAMBDA (DB 0)
          (AND ("aElementOf" (DB 0) "xM") (NOT ("aElementOf" (DB 0) "xN"))))))))
("aFunction" "xf")
("aSubsetOf" "xM" ("szDzozmlpdtrp" "xf"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtcflbdtrb" "xf" "xM")))
  (AND ("aSet" (DB 0))
       ("=" (DB 0)
        (LAMBDA (DB 0)
          (REPLACEMENT TAG
           (EXISTS (DB 0)
            (AND ("aElementOf" (DB 0) "xM")
                 ("=" (DB 1) ("sdtlbdtrb" "xf" (DB 0)))))))))))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aCardinal" (DB 0))) ("aSet" (DB 0))))
(AND ("aCardinal" "xA") ("aCardinal" "xB"))
(IMPLIES (HEADTERM TAG ("sdtlsdt" "xA" "xB")) TRUTH)
(AND (AND ("aCardinal" "xA") ("aCardinal" "xB")) ("aCardinal" "xC"))
(IMPLIES (AND ("sdtlsdt" "xA" "xB") ("sdtlsdt" "xB" "xC"))
 ("sdtlsdt" "xA" "xC"))
(AND ("aCardinal" "xA") ("aCardinal" "xB"))
(OR (OR ("sdtlsdt" "xA" "xB") ("sdtlsdt" "xB" "xA")) ("=" "xB" "xA"))
("aSet" "xM")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("ttheCardinalityOf" "xM")))
  ("aCardinal" (DB 0))))
("aFunction" "xf")
("aSubsetOf" "xM" ("szDzozmlpdtrp" "xf"))
(OR
 ("=" ("ttheCardinalityOf" ("sdtcflbdtrb" "xf" "xM"))
  ("ttheCardinalityOf" "xM"))
 ("sdtlsdt" ("ttheCardinalityOf" ("sdtcflbdtrb" "xf" "xM"))
  ("ttheCardinalityOf" "xM")))
(AND ("aSet" "xN") ("aSet" "xM"))
("sdtlsdt" ("ttheCardinalityOf" "xN") ("ttheCardinalityOf" "xM"))
(EXISTS (DB 0) ("aElementOf" (DB 0) ("sdtbsdt" "xM" "xN")))
(AND ("aSet" "xM") ("aSet" "xN"))
(OR ("=" ("ttheCardinalityOf" "xM") ("ttheCardinalityOf" "xN"))
    ("sdtlsdt" ("ttheCardinalityOf" "xM") ("ttheCardinalityOf" "xN")))
(EXISTS (DB 0) ("aElementOf" (DB 0) "xM"))
(EXISTS (DB 0)
 (AND ("aFunction" (DB 0))
      (AND ("=" "xN" ("szDzozmlpdtrp" (DB 0)))
           ("=" "xM" ("sdtcflbdtrb" (DB 0) ("szDzozmlpdtrp" (DB 0)))))))
("aCardinal" "xA")
("=" ("ttheCardinalityOf" "xA") "xA")
("aSet" "xD")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aSequenceOfCardinalsOn" (DB 0) "xD"))
  (AND ("aFunction" (DB 0))
       (AND ("=" ("szDzozmlpdtrp" (DB 0)) "xD")
            (FORALL (DB 0)
             (IMPLIES ("aElementOf" (DB 0) "xD")
              ("aCardinal" ("sdtlbdtrb" (DB 1) (DB 0)))))))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("szSzuzmzSzeztlpdtcmdtrp" "xkappa" "xD")))
  ("aSet" (DB 0))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IFF ("aElementOf" (DB 0) ("szSzuzmzSzeztlpdtcmdtrp" "xkappa" "xD"))
  (EXISTS (DB 0)
   (EXISTS (DB 0)
    (AND
     (AND ("aElementOf" (DB 0) "xD")
          ("aElementOf" (DB 1) ("sdtlbdtrb" "xkappa" (DB 0))))
     ("=" (DB 2) ("slpdtcmdtrp" (DB 1) (DB 0))))))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("szSzuzmlpdtcmdtrp" "xkappa" "xD")))
  ("=" (DB 0) ("ttheCardinalityOf" ("szSzuzmzSzeztlpdtcmdtrp" "xkappa" "xD")))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IMPLIES
  (HEADTERM TAG ("=" (DB 0) ("szPzrzozdzSzeztlpdtcmdtrp" "xkappa" "xD")))
  ("aSet" (DB 0))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IFF ("aElementOf" (DB 0) ("szPzrzozdzSzeztlpdtcmdtrp" "xkappa" "xD"))
  (AND ("aFunction" (DB 0))
       (AND ("=" ("szDzozmlpdtrp" (DB 0)) "xD")
            (FORALL (DB 0)
             (IMPLIES ("aElementOf" (DB 0) "xD")
              ("aElementOf" ("sdtlbdtrb" (DB 1) (DB 0))
               ("sdtlbdtrb" "xkappa" (DB 0)))))))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("szPzrzozdlpdtcmdtrp" "xkappa" "xD")))
  ("=" (DB 0)
   ("ttheCardinalityOf" ("szPzrzozdzSzeztlpdtcmdtrp" "xkappa" "xD")))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xlambda" "xD")
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) "xD")
  (EXISTS (DB 0) ("aElementOf" (DB 0) ("sdtlbdtrb" "xlambda" (DB 1))))))
(EXISTS (DB 0)
 ("aElementOf" (DB 0) ("szPzrzozdzSzeztlpdtcmdtrp" "xlambda" "xD")))
(AND (AND ("aFunction" "xf") (DOMAIN TAG ("=" ("szDzozmlpdtrp" "xf") "xD")))
     (FORALL (DB 0)
      (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xf"))
       (EXISTS (DB 0)
        (AND ("aElementOf" (DB 0) ("sdtlbdtrb" "xlambda" (DB 1)))
             (EVALUATION TAG ("=" ("sdtlbdtrb" "xf" (DB 1)) (DB 0))))))))
("aElementOf" "xf" ("szPzrzozdzSzeztlpdtcmdtrp" "xlambda" "xD"))
("aSet" "xD")
(AND ("aSequenceOfCardinalsOn" "xkappa" "xD")
     ("aSequenceOfCardinalsOn" "xlambda" "xD"))
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) "xD")
  ("sdtlsdt" ("sdtlbdtrb" "xkappa" (DB 0)) ("sdtlbdtrb" "xlambda" (DB 0)))))
("sdtlsdt" ("szSzuzmlpdtcmdtrp" "xkappa" "xD")
 ("szPzrzozdlpdtcmdtrp" "xlambda" "xD"))
(NOT ("#TH#"))
(OR
 ("=" ("szPzrzozdlpdtcmdtrp" "xlambda" "xD")
  ("szSzuzmlpdtcmdtrp" "xkappa" "xD"))
 ("sdtlsdt" ("szPzrzozdlpdtcmdtrp" "xlambda" "xD")
  ("szSzuzmlpdtcmdtrp" "xkappa" "xD")))
(AND ("aFunction" "xG")
     (AND
      ("=" ("szSzuzmzSzeztlpdtcmdtrp" "xkappa" "xD") ("szDzozmlpdtrp" "xG"))
      ("=" ("szPzrzozdzSzeztlpdtcmdtrp" "xlambda" "xD")
       ("sdtcflbdtrb" "xG" ("szDzozmlpdtrp" "xG")))))
(EXISTS (DB 0)
 ("aElementOf" (DB 0) ("szPzrzozdzSzeztlpdtcmdtrp" "xlambda" "xD")))
(AND
 (AND ("aFunction" "xDiag") (DOMAIN TAG ("=" ("szDzozmlpdtrp" "xDiag") "xD")))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xDiag"))
   (EXISTS (DB 0)
    (AND
     (DEFINED TAG
      (AND ("aSet" (DB 0))
           ("=" (DB 0)
            (LAMBDA (DB 0)
              (REPLACEMENT TAG
               (EXISTS (DB 0)
                (AND ("aElementOf" (DB 0) ("sdtlbdtrb" "xkappa" "xi"))
                     ("=" (DB 1)
                      ("sdtlbdtrb"
                       ("sdtlbdtrb" "xG" ("slpdtcmdtrp" (DB 0) "xi"))
                       "xi")))))))))
     (EVALUATION TAG ("=" ("sdtlbdtrb" "xDiag" (DB 1)) (DB 0))))))))
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) "xD")
  ("sdtlsdt" ("ttheCardinalityOf" ("sdtlbdtrb" "xDiag" (DB 0)))
   ("sdtlbdtrb" "xlambda" (DB 0)))))
("aElementOf" "xi" "xD")
(AND
 (AND ("aFunction" "xF")
      (DOMAIN TAG ("=" ("szDzozmlpdtrp" "xF") ("sdtlbdtrb" "xkappa" "xi"))))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xF"))
   (EVALUATION TAG
    ("=" ("sdtlbdtrb" "xF" (DB 0))
     ("sdtlbdtrb" ("sdtlbdtrb" "xG" ("slpdtcmdtrp" (DB 0) "xi")) "xi"))))))
("=" ("sdtcflbdtrb" "xF" ("sdtlbdtrb" "xkappa" "xi"))
 ("sdtlbdtrb" "xDiag" "xi"))
(AND (AND ("aFunction" "xf") (DOMAIN TAG ("=" ("szDzozmlpdtrp" "xf") "xD")))
     (FORALL (DB 0)
      (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xf"))
       (EXISTS (DB 0)
        (AND
         ("aElementOf" (DB 0)
          ("sdtbsdt" ("sdtlbdtrb" "xlambda" (DB 1))
           ("sdtlbdtrb" "xDiag" (DB 1))))
         (EVALUATION TAG ("=" ("sdtlbdtrb" "xf" (DB 1)) (DB 0))))))))
("aElementOf" "xf" ("szPzrzozdzSzeztlpdtcmdtrp" "xlambda" "xD"))
(AND ("aElementOf" "xj" "xD")
     (AND ("aElementOf" "xm" ("sdtlbdtrb" "xkappa" "xj"))
          ("=" ("sdtlbdtrb" "xG" ("slpdtcmdtrp" "xm" "xj")) "xf")))
(AND
 ("aElementOf" ("sdtlbdtrb" ("sdtlbdtrb" "xG" ("slpdtcmdtrp" "xm" "xj")) "xj")
  ("sdtlbdtrb" "xDiag" "xj"))
 (NOT ("aElementOf" ("sdtlbdtrb" "xf" "xj") ("sdtlbdtrb" "xDiag" "xj"))))
("aSet" "xM")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aSubsetOf" (DB 0) "xM"))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElementOf" (DB 0) (DB 1)) ("aElementOf" (DB 0) "xM"))))))
(AND ("aSet" "xM") ("aSet" "xN"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtbsdt" "xM" "xN")))
  (AND ("aSet" (DB 0))
       ("=" (DB 0)
        (LAMBDA (DB 0)
          (AND ("aElementOf" (DB 0) "xM") (NOT ("aElementOf" (DB 0) "xN"))))))))
("aFunction" "xf")
("aSubsetOf" "xM" ("szDzozmlpdtrp" "xf"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtcflbdtrb" "xf" "xM")))
  (AND ("aSet" (DB 0))
       ("=" (DB 0)
        (LAMBDA (DB 0)
          (REPLACEMENT TAG
           (EXISTS (DB 0)
            (AND ("aElementOf" (DB 0) "xM")
                 ("=" (DB 1) ("sdtlbdtrb" "xf" (DB 0)))))))))))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aCardinal" (DB 0))) ("aSet" (DB 0))))
(AND ("aCardinal" "xA") ("aCardinal" "xB"))
(IMPLIES (HEADTERM TAG ("sdtlsdt" "xA" "xB")) TRUTH)
(AND (AND ("aCardinal" "xA") ("aCardinal" "xB")) ("aCardinal" "xC"))
(IMPLIES (AND ("sdtlsdt" "xA" "xB") ("sdtlsdt" "xB" "xC"))
 ("sdtlsdt" "xA" "xC"))
(AND ("aCardinal" "xA") ("aCardinal" "xB"))
(OR (OR ("sdtlsdt" "xA" "xB") ("sdtlsdt" "xB" "xA")) ("=" "xB" "xA"))
("aSet" "xM")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("ttheCardinalityOf" "xM")))
  ("aCardinal" (DB 0))))
("aFunction" "xf")
("aSubsetOf" "xM" ("szDzozmlpdtrp" "xf"))
(OR
 ("=" ("ttheCardinalityOf" ("sdtcflbdtrb" "xf" "xM"))
  ("ttheCardinalityOf" "xM"))
 ("sdtlsdt" ("ttheCardinalityOf" ("sdtcflbdtrb" "xf" "xM"))
  ("ttheCardinalityOf" "xM")))
(AND ("aSet" "xN") ("aSet" "xM"))
("sdtlsdt" ("ttheCardinalityOf" "xN") ("ttheCardinalityOf" "xM"))
(EXISTS (DB 0) ("aElementOf" (DB 0) ("sdtbsdt" "xM" "xN")))
(AND ("aSet" "xM") ("aSet" "xN"))
(OR ("=" ("ttheCardinalityOf" "xM") ("ttheCardinalityOf" "xN"))
    ("sdtlsdt" ("ttheCardinalityOf" "xM") ("ttheCardinalityOf" "xN")))
(EXISTS (DB 0) ("aElementOf" (DB 0) "xM"))
(EXISTS (DB 0)
 (AND ("aFunction" (DB 0))
      (AND ("=" "xN" ("szDzozmlpdtrp" (DB 0)))
           ("=" "xM" ("sdtcflbdtrb" (DB 0) ("szDzozmlpdtrp" (DB 0)))))))
("aCardinal" "xA")
("=" ("ttheCardinalityOf" "xA") "xA")
("aSet" "xD")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aSequenceOfCardinalsOn" (DB 0) "xD"))
  (AND ("aFunction" (DB 0))
       (AND ("=" ("szDzozmlpdtrp" (DB 0)) "xD")
            (FORALL (DB 0)
             (IMPLIES ("aElementOf" (DB 0) "xD")
              ("aCardinal" ("sdtlbdtrb" (DB 1) (DB 0)))))))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("szSzuzmzSzeztlpdtcmdtrp" "xkappa" "xD")))
  ("aSet" (DB 0))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IFF ("aElementOf" (DB 0) ("szSzuzmzSzeztlpdtcmdtrp" "xkappa" "xD"))
  (EXISTS (DB 0)
   (EXISTS (DB 0)
    (AND
     (AND ("aElementOf" (DB 0) "xD")
          ("aElementOf" (DB 1) ("sdtlbdtrb" "xkappa" (DB 0))))
     ("=" (DB 2) ("slpdtcmdtrp" (DB 1) (DB 0))))))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("szSzuzmlpdtcmdtrp" "xkappa" "xD")))
  ("=" (DB 0) ("ttheCardinalityOf" ("szSzuzmzSzeztlpdtcmdtrp" "xkappa" "xD")))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IMPLIES
  (HEADTERM TAG ("=" (DB 0) ("szPzrzozdzSzeztlpdtcmdtrp" "xkappa" "xD")))
  ("aSet" (DB 0))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IFF ("aElementOf" (DB 0) ("szPzrzozdzSzeztlpdtcmdtrp" "xkappa" "xD"))
  (AND ("aFunction" (DB 0))
       (AND ("=" ("szDzozmlpdtrp" (DB 0)) "xD")
            (FORALL (DB 0)
             (IMPLIES ("aElementOf" (DB 0) "xD")
              ("aElementOf" ("sdtlbdtrb" (DB 1) (DB 0))
               ("sdtlbdtrb" "xkappa" (DB 0)))))))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xkappa" "xD")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("szPzrzozdlpdtcmdtrp" "xkappa" "xD")))
  ("=" (DB 0)
   ("ttheCardinalityOf" ("szPzrzozdzSzeztlpdtcmdtrp" "xkappa" "xD")))))
("aSet" "xD")
("aSequenceOfCardinalsOn" "xlambda" "xD")
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) "xD")
  (EXISTS (DB 0) ("aElementOf" (DB 0) ("sdtlbdtrb" "xlambda" (DB 1))))))
(EXISTS (DB 0)
 ("aElementOf" (DB 0) ("szPzrzozdzSzeztlpdtcmdtrp" "xlambda" "xD")))
(AND (AND ("aFunction" "xf") (DOMAIN TAG ("=" ("szDzozmlpdtrp" "xf") "xD")))
     (FORALL (DB 0)
      (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xf"))
       (EXISTS (DB 0)
        (AND ("aElementOf" (DB 0) ("sdtlbdtrb" "xlambda" (DB 1)))
             (EVALUATION TAG ("=" ("sdtlbdtrb" "xf" (DB 1)) (DB 0))))))))
("aElementOf" "xf" ("szPzrzozdzSzeztlpdtcmdtrp" "xlambda" "xD"))
("aSet" "xD")
(AND ("aSequenceOfCardinalsOn" "xkappa" "xD")
     ("aSequenceOfCardinalsOn" "xlambda" "xD"))
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) "xD")
  ("sdtlsdt" ("sdtlbdtrb" "xkappa" (DB 0)) ("sdtlbdtrb" "xlambda" (DB 0)))))
("sdtlsdt" ("szSzuzmlpdtcmdtrp" "xkappa" "xD")
 ("szPzrzozdlpdtcmdtrp" "xlambda" "xD"))
(NOT ("#TH#"))
(OR
 ("=" ("szPzrzozdlpdtcmdtrp" "xlambda" "xD")
  ("szSzuzmlpdtcmdtrp" "xkappa" "xD"))
 ("sdtlsdt" ("szPzrzozdlpdtcmdtrp" "xlambda" "xD")
  ("szSzuzmlpdtcmdtrp" "xkappa" "xD")))
(AND ("aFunction" "xG")
     (AND
      ("=" ("szSzuzmzSzeztlpdtcmdtrp" "xkappa" "xD") ("szDzozmlpdtrp" "xG"))
      ("=" ("szPzrzozdzSzeztlpdtcmdtrp" "xlambda" "xD")
       ("sdtcflbdtrb" "xG" ("szDzozmlpdtrp" "xG")))))
(EXISTS (DB 0)
 ("aElementOf" (DB 0) ("szPzrzozdzSzeztlpdtcmdtrp" "xlambda" "xD")))
(AND
 (AND ("aFunction" "xDiag") (DOMAIN TAG ("=" ("szDzozmlpdtrp" "xDiag") "xD")))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xDiag"))
   (EXISTS (DB 0)
    (AND
     (DEFINED TAG
      (AND ("aSet" (DB 0))
           ("=" (DB 0)
            (LAMBDA (DB 0)
              (REPLACEMENT TAG
               (EXISTS (DB 0)
                (AND ("aElementOf" (DB 0) ("sdtlbdtrb" "xkappa" "xi"))
                     ("=" (DB 1)
                      ("sdtlbdtrb"
                       ("sdtlbdtrb" "xG" ("slpdtcmdtrp" (DB 0) "xi"))
                       "xi")))))))))
     (EVALUATION TAG ("=" ("sdtlbdtrb" "xDiag" (DB 1)) (DB 0))))))))
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) "xD")
  ("sdtlsdt" ("ttheCardinalityOf" ("sdtlbdtrb" "xDiag" (DB 0)))
   ("sdtlbdtrb" "xlambda" (DB 0)))))
("aElementOf" "xi" "xD")
(AND
 (AND ("aFunction" "xF")
      (DOMAIN TAG ("=" ("szDzozmlpdtrp" "xF") ("sdtlbdtrb" "xkappa" "xi"))))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xF"))
   (EVALUATION TAG
    ("=" ("sdtlbdtrb" "xF" (DB 0))
     ("sdtlbdtrb" ("sdtlbdtrb" "xG" ("slpdtcmdtrp" (DB 0) "xi")) "xi"))))))
("=" ("sdtcflbdtrb" "xF" ("sdtlbdtrb" "xkappa" "xi"))
 ("sdtlbdtrb" "xDiag" "xi"))
(AND (AND ("aFunction" "xf") (DOMAIN TAG ("=" ("szDzozmlpdtrp" "xf") "xD")))
     (FORALL (DB 0)
      (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xf"))
       (EXISTS (DB 0)
        (AND
         ("aElementOf" (DB 0)
          ("sdtbsdt" ("sdtlbdtrb" "xlambda" (DB 1))
           ("sdtlbdtrb" "xDiag" (DB 1))))
         (EVALUATION TAG ("=" ("sdtlbdtrb" "xf" (DB 1)) (DB 0))))))))
("aElementOf" "xf" ("szPzrzozdzSzeztlpdtcmdtrp" "xlambda" "xD"))
(AND ("aElementOf" "xj" "xD")
     (AND ("aElementOf" "xm" ("sdtlbdtrb" "xkappa" "xj"))
          ("=" ("sdtlbdtrb" "xG" ("slpdtcmdtrp" "xm" "xj")) "xf")))
(AND
 ("aElementOf" ("sdtlbdtrb" ("sdtlbdtrb" "xG" ("slpdtcmdtrp" "xm" "xj")) "xj")
  ("sdtlbdtrb" "xDiag" "xj"))
 (NOT ("aElementOf" ("sdtlbdtrb" "xf" "xj") ("sdtlbdtrb" "xDiag" "xj"))))
