("aSet" "xM")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aSubsetOf" (DB 0) "xM"))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElementOf" (DB 0) (DB 1)) ("aElementOf" (DB 0) "xM"))))))
("aFunction" "xf")
("aSubsetOf" "xM" ("szDzozmlpdtrp" "xf"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtcflbdtrb" "xf" "xM")))
  (AND ("aSet" (DB 0))
       ("=" (DB 0)
        (LAMBDA (DB 0)
          (REPLACEMENT TAG
           (EXISTS (DB 0)
            (AND ("aElementOf" (DB 0) "xM")
                 ("=" (DB 1) ("sdtlbdtrb" "xf" (DB 0)))))))))))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aComplexNumber" (DB 0))) TRUTH))
("aFunction" "xf")
(AND
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xf"))
   ("aComplexNumber" (DB 0))))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xf"))
   ("aComplexNumber" ("sdtlbdtrb" "xf" (DB 0))))))
("aSet" "xM")
(FORALL (DB 0) (IMPLIES ("aElementOf" (DB 0) "xM") ("aComplexNumber" (DB 0))))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aRealNumber" (DB 0))) TRUTH))
("aComplexNumber" "xz")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sbrdtbr" "xz"))) ("aRealNumber" (DB 0))))
("aRealNumber" "xx")
(IMPLIES (HEADTERM TAG ("isPositive" "xx")) TRUTH)
(AND ("aRealNumber" "xx") ("aRealNumber" "xy"))
(IMPLIES (HEADTERM TAG ("sdtlsdt" "xx" "xy")) TRUTH)
(AND ("aRealNumber" "xx") ("aRealNumber" "xy"))
(IMPLIES ("sdtlsdt" "xx" "xy") (NOT ("sdtlsdt" "xy" "xx")))
("aFunction" "xf")
(IMPLIES (HEADTERM TAG ("isHolomorphic" "xf")) TRUTH)
(AND (AND ("aRealNumber" "xeps") ("isPositive" "xeps")) ("aComplexNumber" "xz"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("szBzazlzllpdtcmdtrp" "xeps" "xz")))
  (AND ("aSet" (DB 0)) ("aElementOf" "xz" (DB 0)))))
(AND (AND ("aRealNumber" "xeps") ("isPositive" "xeps")) ("aComplexNumber" "xz"))
(EXISTS (DB 0)
 (AND ("aElementOf" (DB 0) ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
      ("sdtlsdt" ("sbrdtbr" "xz") ("sbrdtbr" (DB 0)))))
("aSet" "xM")
(IFF (HEADTERM TAG ("isOpen" "xM"))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) "xM")
   (EXISTS (DB 0)
    (AND (AND ("aRealNumber" (DB 0)) ("isPositive" (DB 0)))
         ("aSubsetOf" ("szBzazlzllpdtcmdtrp" (DB 0) (DB 1)) "xM"))))))
(AND (AND ("aRealNumber" "xeps") ("isPositive" "xeps")) ("aComplexNumber" "xz"))
("isOpen" ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
("aFunction" "xf")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aLocalMaximalPointOf" (DB 0) "xf"))
  (AND ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xf"))
       (EXISTS (DB 0)
        (AND (AND ("aRealNumber" (DB 0)) ("isPositive" (DB 0)))
             (AND
              ("aSubsetOf" ("szBzazlzllpdtcmdtrp" (DB 0) (DB 1))
               ("szDzozmlpdtrp" "xf"))
              (FORALL (DB 0)
               (IMPLIES
                ("aElementOf" (DB 0) ("szBzazlzllpdtcmdtrp" (DB 1) (DB 2)))
                (OR
                 ("=" ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 0)))
                  ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 2))))
                 ("sdtlsdt" ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 0)))
                  ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 2)))))))))))))
("aFunction" "xf")
("aSubsetOf" "xU" ("szDzozmlpdtrp" "xf"))
(IFF (HEADTERM TAG ("isConstantOn" "xf" "xU"))
 (EXISTS (DB 0)
  (AND ("aComplexNumber" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElementOf" (DB 0) "xU")
         ("=" ("sdtlbdtrb" "xf" (DB 0)) (DB 1)))))))
(AND
 (AND ("aFunction" "xf") (AND ("aRealNumber" "xeps") ("isPositive" "xeps")))
 ("aComplexNumber" "xz"))
(AND ("isHolomorphic" "xf")
     ("aSubsetOf" ("szBzazlzllpdtcmdtrp" "xeps" "xz") ("szDzozmlpdtrp" "xf")))
(IMPLIES (NOT ("isConstantOn" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz")))
 ("isOpen" ("sdtcflbdtrb" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz"))))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("aRegion" (DB 0)))
  (AND ("aSet" (DB 0)) ("isOpen" (DB 0)))))
("aFunction" "xf")
(AND ("isHolomorphic" "xf") ("aRegion" ("szDzozmlpdtrp" "xf")))
(AND (AND ("aRealNumber" "xeps") ("isPositive" "xeps")) ("aComplexNumber" "xz"))
("aSubsetOf" ("szBzazlzllpdtcmdtrp" "xeps" "xz") ("szDzozmlpdtrp" "xf"))
(IMPLIES ("isConstantOn" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
 ("isConstantOn" "xf" ("szDzozmlpdtrp" "xf")))
("aFunction" "xf")
(AND ("isHolomorphic" "xf") ("aRegion" ("szDzozmlpdtrp" "xf")))
(IMPLIES (EXISTS (DB 0) ("aLocalMaximalPointOf" (DB 0) "xf"))
 ("isConstantOn" "xf" ("szDzozmlpdtrp" "xf")))
("aLocalMaximalPointOf" "xz" "xf")
(AND (AND ("aRealNumber" "xeps") ("isPositive" "xeps"))
     (AND
      ("aSubsetOf" ("szBzazlzllpdtcmdtrp" "xeps" "xz") ("szDzozmlpdtrp" "xf"))
      (FORALL (DB 0)
       (IMPLIES ("aElementOf" (DB 0) ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
        (OR
         ("=" ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 0)))
          ("sbrdtbr" ("sdtlbdtrb" "xf" "xz")))
         ("sdtlsdt" ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 0)))
          ("sbrdtbr" ("sdtlbdtrb" "xf" "xz"))))))))
("isConstantOn" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
(NOT ("#TH#"))
("isOpen" ("sdtcflbdtrb" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz")))
(AND (AND ("aRealNumber" "xdelta") ("isPositive" "xdelta"))
     ("aSubsetOf" ("szBzazlzllpdtcmdtrp" "xdelta" ("sdtlbdtrb" "xf" "xz"))
      ("sdtcflbdtrb" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz"))))
(EXISTS (DB 0)
 (AND ("aElementOf" (DB 0) ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
      ("sdtlsdt" ("sbrdtbr" ("sdtlbdtrb" "xf" "xz"))
       ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 0))))))
("isConstantOn" "xf" ("szDzozmlpdtrp" "xf"))
("aSet" "xM")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aSubsetOf" (DB 0) "xM"))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElementOf" (DB 0) (DB 1)) ("aElementOf" (DB 0) "xM"))))))
("aFunction" "xf")
("aSubsetOf" "xM" ("szDzozmlpdtrp" "xf"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtcflbdtrb" "xf" "xM")))
  (AND ("aSet" (DB 0))
       ("=" (DB 0)
        (LAMBDA (DB 0)
          (REPLACEMENT TAG
           (EXISTS (DB 0)
            (AND ("aElementOf" (DB 0) "xM")
                 ("=" (DB 1) ("sdtlbdtrb" "xf" (DB 0)))))))))))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aComplexNumber" (DB 0))) TRUTH))
("aFunction" "xf")
(AND
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xf"))
   ("aComplexNumber" (DB 0))))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xf"))
   ("aComplexNumber" ("sdtlbdtrb" "xf" (DB 0))))))
("aSet" "xM")
(FORALL (DB 0) (IMPLIES ("aElementOf" (DB 0) "xM") ("aComplexNumber" (DB 0))))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aRealNumber" (DB 0))) TRUTH))
("aComplexNumber" "xz")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sbrdtbr" "xz"))) ("aRealNumber" (DB 0))))
("aRealNumber" "xx")
(IMPLIES (HEADTERM TAG ("isPositive" "xx")) TRUTH)
(AND ("aRealNumber" "xx") ("aRealNumber" "xy"))
(IMPLIES (HEADTERM TAG ("sdtlsdt" "xx" "xy")) TRUTH)
(AND ("aRealNumber" "xx") ("aRealNumber" "xy"))
(IMPLIES ("sdtlsdt" "xx" "xy") (NOT ("sdtlsdt" "xy" "xx")))
("aFunction" "xf")
(IMPLIES (HEADTERM TAG ("isHolomorphic" "xf")) TRUTH)
(AND (AND ("aRealNumber" "xeps") ("isPositive" "xeps")) ("aComplexNumber" "xz"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("szBzazlzllpdtcmdtrp" "xeps" "xz")))
  (AND ("aSet" (DB 0)) ("aElementOf" "xz" (DB 0)))))
(AND (AND ("aRealNumber" "xeps") ("isPositive" "xeps")) ("aComplexNumber" "xz"))
(EXISTS (DB 0)
 (AND ("aElementOf" (DB 0) ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
      ("sdtlsdt" ("sbrdtbr" "xz") ("sbrdtbr" (DB 0)))))
("aSet" "xM")
(IFF (HEADTERM TAG ("isOpen" "xM"))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) "xM")
   (EXISTS (DB 0)
    (AND (AND ("aRealNumber" (DB 0)) ("isPositive" (DB 0)))
         ("aSubsetOf" ("szBzazlzllpdtcmdtrp" (DB 0) (DB 1)) "xM"))))))
(AND (AND ("aRealNumber" "xeps") ("isPositive" "xeps")) ("aComplexNumber" "xz"))
("isOpen" ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
("aFunction" "xf")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aLocalMaximalPointOf" (DB 0) "xf"))
  (AND ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xf"))
       (EXISTS (DB 0)
        (AND (AND ("aRealNumber" (DB 0)) ("isPositive" (DB 0)))
             (AND
              ("aSubsetOf" ("szBzazlzllpdtcmdtrp" (DB 0) (DB 1))
               ("szDzozmlpdtrp" "xf"))
              (FORALL (DB 0)
               (IMPLIES
                ("aElementOf" (DB 0) ("szBzazlzllpdtcmdtrp" (DB 1) (DB 2)))
                (OR
                 ("=" ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 0)))
                  ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 2))))
                 ("sdtlsdt" ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 0)))
                  ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 2)))))))))))))
("aFunction" "xf")
("aSubsetOf" "xU" ("szDzozmlpdtrp" "xf"))
(IFF (HEADTERM TAG ("isConstantOn" "xf" "xU"))
 (EXISTS (DB 0)
  (AND ("aComplexNumber" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElementOf" (DB 0) "xU")
         ("=" ("sdtlbdtrb" "xf" (DB 0)) (DB 1)))))))
(AND
 (AND ("aFunction" "xf") (AND ("aRealNumber" "xeps") ("isPositive" "xeps")))
 ("aComplexNumber" "xz"))
(AND ("isHolomorphic" "xf")
     ("aSubsetOf" ("szBzazlzllpdtcmdtrp" "xeps" "xz") ("szDzozmlpdtrp" "xf")))
(IMPLIES (NOT ("isConstantOn" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz")))
 ("isOpen" ("sdtcflbdtrb" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz"))))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("aRegion" (DB 0)))
  (AND ("aSet" (DB 0)) ("isOpen" (DB 0)))))
("aFunction" "xf")
(AND ("isHolomorphic" "xf") ("aRegion" ("szDzozmlpdtrp" "xf")))
(AND (AND ("aRealNumber" "xeps") ("isPositive" "xeps")) ("aComplexNumber" "xz"))
("aSubsetOf" ("szBzazlzllpdtcmdtrp" "xeps" "xz") ("szDzozmlpdtrp" "xf"))
(IMPLIES ("isConstantOn" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
 ("isConstantOn" "xf" ("szDzozmlpdtrp" "xf")))
("aFunction" "xf")
(AND ("isHolomorphic" "xf") ("aRegion" ("szDzozmlpdtrp" "xf")))
(IMPLIES (EXISTS (DB 0) ("aLocalMaximalPointOf" (DB 0) "xf"))
 ("isConstantOn" "xf" ("szDzozmlpdtrp" "xf")))
("aLocalMaximalPointOf" "xz" "xf")
(AND (AND ("aRealNumber" "xeps") ("isPositive" "xeps"))
     (AND
      ("aSubsetOf" ("szBzazlzllpdtcmdtrp" "xeps" "xz") ("szDzozmlpdtrp" "xf"))
      (FORALL (DB 0)
       (IMPLIES ("aElementOf" (DB 0) ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
        (OR
         ("=" ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 0)))
          ("sbrdtbr" ("sdtlbdtrb" "xf" "xz")))
         ("sdtlsdt" ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 0)))
          ("sbrdtbr" ("sdtlbdtrb" "xf" "xz"))))))))
("isConstantOn" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
(NOT ("#TH#"))
("isOpen" ("sdtcflbdtrb" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz")))
(AND (AND ("aRealNumber" "xdelta") ("isPositive" "xdelta"))
     ("aSubsetOf" ("szBzazlzllpdtcmdtrp" "xdelta" ("sdtlbdtrb" "xf" "xz"))
      ("sdtcflbdtrb" "xf" ("szBzazlzllpdtcmdtrp" "xeps" "xz"))))
(EXISTS (DB 0)
 (AND ("aElementOf" (DB 0) ("szBzazlzllpdtcmdtrp" "xeps" "xz"))
      ("sdtlsdt" ("sbrdtbr" ("sdtlbdtrb" "xf" "xz"))
       ("sbrdtbr" ("sdtlbdtrb" "xf" (DB 0))))))
("isConstantOn" "xf" ("szDzozmlpdtrp" "xf"))
