(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aElement" (DB 0))) TRUTH))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aRewritingSystem" (DB 0))) TRUTH))
(AND ("aElement" "xx") ("aRewritingSystem" "xR"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("aReductOfIn" (DB 0) "xx" "xR")) ("aElement" (DB 0))))
(AND (AND ("aElement" "xx") ("aRewritingSystem" "xR")) ("aElement" "xy"))
(IMPLIES (HEADTERM TAG ("sdtmndtplgtdt" "xx" "xR" "xy")) TRUTH)
(AND (AND ("aElement" "xx") ("aRewritingSystem" "xR")) ("aElement" "xy"))
(IFF ("sdtmndtplgtdt" "xx" "xR" "xy")
 (OR ("aReductOfIn" "xy" "xx" "xR")
     (EXISTS (DB 0)
      (AND ("aElement" (DB 0))
           (AND ("aReductOfIn" (DB 0) "xx" "xR")
                ("sdtmndtplgtdt" (DB 0) "xR" "xy"))))))
(AND (AND (AND ("aElement" "xx") ("aRewritingSystem" "xR")) ("aElement" "xy"))
     ("aElement" "xz"))
(IMPLIES
 (AND ("sdtmndtplgtdt" "xx" "xR" "xy") ("sdtmndtplgtdt" "xy" "xR" "xz"))
 ("sdtmndtplgtdt" "xx" "xR" "xz"))
(AND (AND ("aElement" "xx") ("aRewritingSystem" "xR")) ("aElement" "xy"))
(IFF (HEADTERM TAG ("sdtmndtasgtdt" "xx" "xR" "xy"))
 (OR ("=" "xx" "xy") ("sdtmndtplgtdt" "xx" "xR" "xy")))
(AND (AND (AND ("aElement" "xx") ("aRewritingSystem" "xR")) ("aElement" "xy"))
     ("aElement" "xz"))
(IMPLIES
 (AND ("sdtmndtasgtdt" "xx" "xR" "xy") ("sdtmndtasgtdt" "xy" "xR" "xz"))
 ("sdtmndtasgtdt" "xx" "xR" "xz"))
("aRewritingSystem" "xR")
(IFF (HEADTERM TAG ("isConfluent" "xR"))
 (FORALL (DB 0)
  (FORALL (DB 0)
   (FORALL (DB 0)
    (IMPLIES
     (AND
      (AND (AND ("aElement" (DB 2)) ("aElement" (DB 1))) ("aElement" (DB 0)))
      (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 1))
           ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))))
     (EXISTS (DB 0)
      (AND ("aElement" (DB 0))
           (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))
                ("sdtmndtasgtdt" (DB 1) "xR" (DB 0))))))))))
("aRewritingSystem" "xR")
(IFF (HEADTERM TAG ("isLocallyConfluent" "xR"))
 (FORALL (DB 0)
  (FORALL (DB 0)
   (FORALL (DB 0)
    (IMPLIES
     (AND
      (AND (AND ("aElement" (DB 2)) ("aElement" (DB 1))) ("aElement" (DB 0)))
      (AND ("aReductOfIn" (DB 1) (DB 2) "xR")
           ("aReductOfIn" (DB 0) (DB 2) "xR")))
     (EXISTS (DB 0)
      (AND ("aElement" (DB 0))
           (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))
                ("sdtmndtasgtdt" (DB 1) "xR" (DB 0))))))))))
("aRewritingSystem" "xR")
(IFF (HEADTERM TAG ("isTerminating" "xR"))
 (FORALL (DB 0)
  (FORALL (DB 0)
   (IMPLIES (AND ("aElement" (DB 1)) ("aElement" (DB 0)))
    (IMPLIES ("sdtmndtplgtdt" (DB 1) "xR" (DB 0)) ("iLess" (DB 0) (DB 1)))))))
(AND ("aElement" "xx") ("aRewritingSystem" "xR"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aNormalFormOfIn" (DB 0) "xx" "xR"))
  (AND ("aElement" (DB 0))
       (AND ("sdtmndtasgtdt" "xx" "xR" (DB 0))
            (NOT (EXISTS (DB 0) ("aReductOfIn" (DB 0) (DB 1) "xR")))))))
(AND ("aRewritingSystem" "xR") ("isTerminating" "xR"))
(FORALL (DB 0)
 (IMPLIES ("aElement" (DB 0))
  (IMPLIES
   (INDUCTIONHYPOTHESIS TAG
    (FORALL (DB 0)
     (IMPLIES ("aElement" (DB 0))
      (IMPLIES ("iLess" (DB 0) (DB 1))
       (EXISTS (DB 0) ("aNormalFormOfIn" (DB 0) (DB 1) "xR"))))))
   (EXISTS (DB 0) ("aNormalFormOfIn" (DB 0) (DB 1) "xR")))))
(FORALL (DB 0)
 (IMPLIES
  (AND ("aRewritingSystem" (DB 0))
       (AND ("isTerminating" (DB 0)) ("isLocallyConfluent" (DB 0))))
  ("isConfluent" (DB 0))))
("aRewritingSystem" "xR")
(AND ("isLocallyConfluent" "xR") ("isTerminating" "xR"))
(FORALL (DB 0)
 (FORALL (DB 0)
  (FORALL (DB 0)
   (IMPLIES
    (AND
     (AND (AND ("aElement" (DB 2)) ("aElement" (DB 1))) ("aElement" (DB 0)))
     (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 1))
          ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))))
    (IMPLIES
     (INDUCTIONHYPOTHESIS TAG
      (FORALL (DB 0)
       (FORALL (DB 0)
        (FORALL (DB 0)
         (IMPLIES
          (AND
           (AND (AND ("aElement" (DB 2)) ("aElement" (DB 1)))
                ("aElement" (DB 0)))
           (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 1))
                ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))))
          (IMPLIES ("iLess" (DB 2) (DB 5))
           (EXISTS (DB 0)
            (AND ("aElement" (DB 0))
                 (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))
                      ("sdtmndtasgtdt" (DB 1) "xR" (DB 0)))))))))))
     (EXISTS (DB 0)
      (AND ("aElement" (DB 0))
           (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))
                ("sdtmndtasgtdt" (DB 1) "xR" (DB 0))))))))))
(AND (AND ("aElement" "xa") ("aElement" "xb")) ("aElement" "xc"))
(AND ("sdtmndtplgtdt" "xa" "xR" "xb") ("sdtmndtplgtdt" "xa" "xR" "xc"))
(AND ("aElement" "xu")
     (AND ("aReductOfIn" "xu" "xa" "xR") ("sdtmndtasgtdt" "xu" "xR" "xb")))
(AND ("aElement" "xv")
     (AND ("aReductOfIn" "xv" "xa" "xR") ("sdtmndtasgtdt" "xv" "xR" "xc")))
(AND ("aElement" "xw")
     (AND ("sdtmndtasgtdt" "xu" "xR" "xw") ("sdtmndtasgtdt" "xv" "xR" "xw")))
("aNormalFormOfIn" "xd" "xw" "xR")
("sdtmndtasgtdt" "xb" "xR" "xd")
(AND ("aElement" "xx")
     (AND ("sdtmndtasgtdt" "xb" "xR" "xx") ("sdtmndtasgtdt" "xd" "xR" "xx")))
("sdtmndtasgtdt" "xc" "xR" "xd")
(AND ("aElement" "xy")
     (AND ("sdtmndtasgtdt" "xc" "xR" "xy") ("sdtmndtasgtdt" "xd" "xR" "xy")))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aElement" (DB 0))) TRUTH))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aRewritingSystem" (DB 0))) TRUTH))
(AND ("aElement" "xx") ("aRewritingSystem" "xR"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("aReductOfIn" (DB 0) "xx" "xR")) ("aElement" (DB 0))))
(AND (AND ("aElement" "xx") ("aRewritingSystem" "xR")) ("aElement" "xy"))
(IMPLIES (HEADTERM TAG ("sdtmndtplgtdt" "xx" "xR" "xy")) TRUTH)
(AND (AND ("aElement" "xx") ("aRewritingSystem" "xR")) ("aElement" "xy"))
(IFF ("sdtmndtplgtdt" "xx" "xR" "xy")
 (OR ("aReductOfIn" "xy" "xx" "xR")
     (EXISTS (DB 0)
      (AND ("aElement" (DB 0))
           (AND ("aReductOfIn" (DB 0) "xx" "xR")
                ("sdtmndtplgtdt" (DB 0) "xR" "xy"))))))
(AND (AND (AND ("aElement" "xx") ("aRewritingSystem" "xR")) ("aElement" "xy"))
     ("aElement" "xz"))
(IMPLIES
 (AND ("sdtmndtplgtdt" "xx" "xR" "xy") ("sdtmndtplgtdt" "xy" "xR" "xz"))
 ("sdtmndtplgtdt" "xx" "xR" "xz"))
(AND (AND ("aElement" "xx") ("aRewritingSystem" "xR")) ("aElement" "xy"))
(IFF (HEADTERM TAG ("sdtmndtasgtdt" "xx" "xR" "xy"))
 (OR ("=" "xx" "xy") ("sdtmndtplgtdt" "xx" "xR" "xy")))
(AND (AND (AND ("aElement" "xx") ("aRewritingSystem" "xR")) ("aElement" "xy"))
     ("aElement" "xz"))
(IMPLIES
 (AND ("sdtmndtasgtdt" "xx" "xR" "xy") ("sdtmndtasgtdt" "xy" "xR" "xz"))
 ("sdtmndtasgtdt" "xx" "xR" "xz"))
("aRewritingSystem" "xR")
(IFF (HEADTERM TAG ("isConfluent" "xR"))
 (FORALL (DB 0)
  (FORALL (DB 0)
   (FORALL (DB 0)
    (IMPLIES
     (AND
      (AND (AND ("aElement" (DB 2)) ("aElement" (DB 1))) ("aElement" (DB 0)))
      (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 1))
           ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))))
     (EXISTS (DB 0)
      (AND ("aElement" (DB 0))
           (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))
                ("sdtmndtasgtdt" (DB 1) "xR" (DB 0))))))))))
("aRewritingSystem" "xR")
(IFF (HEADTERM TAG ("isLocallyConfluent" "xR"))
 (FORALL (DB 0)
  (FORALL (DB 0)
   (FORALL (DB 0)
    (IMPLIES
     (AND
      (AND (AND ("aElement" (DB 2)) ("aElement" (DB 1))) ("aElement" (DB 0)))
      (AND ("aReductOfIn" (DB 1) (DB 2) "xR")
           ("aReductOfIn" (DB 0) (DB 2) "xR")))
     (EXISTS (DB 0)
      (AND ("aElement" (DB 0))
           (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))
                ("sdtmndtasgtdt" (DB 1) "xR" (DB 0))))))))))
("aRewritingSystem" "xR")
(IFF (HEADTERM TAG ("isTerminating" "xR"))
 (FORALL (DB 0)
  (FORALL (DB 0)
   (IMPLIES (AND ("aElement" (DB 1)) ("aElement" (DB 0)))
    (IMPLIES ("sdtmndtplgtdt" (DB 1) "xR" (DB 0)) ("iLess" (DB 0) (DB 1)))))))
(AND ("aElement" "xx") ("aRewritingSystem" "xR"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aNormalFormOfIn" (DB 0) "xx" "xR"))
  (AND ("aElement" (DB 0))
       (AND ("sdtmndtasgtdt" "xx" "xR" (DB 0))
            (NOT (EXISTS (DB 0) ("aReductOfIn" (DB 0) (DB 1) "xR")))))))
(AND ("aRewritingSystem" "xR") ("isTerminating" "xR"))
(FORALL (DB 0)
 (IMPLIES ("aElement" (DB 0))
  (IMPLIES
   (INDUCTIONHYPOTHESIS TAG
    (FORALL (DB 0)
     (IMPLIES ("aElement" (DB 0))
      (IMPLIES ("iLess" (DB 0) (DB 1))
       (EXISTS (DB 0) ("aNormalFormOfIn" (DB 0) (DB 1) "xR"))))))
   (EXISTS (DB 0) ("aNormalFormOfIn" (DB 0) (DB 1) "xR")))))
(FORALL (DB 0)
 (IMPLIES
  (AND ("aRewritingSystem" (DB 0))
       (AND ("isTerminating" (DB 0)) ("isLocallyConfluent" (DB 0))))
  ("isConfluent" (DB 0))))
("aRewritingSystem" "xR")
(AND ("isLocallyConfluent" "xR") ("isTerminating" "xR"))
(FORALL (DB 0)
 (FORALL (DB 0)
  (FORALL (DB 0)
   (IMPLIES
    (AND
     (AND (AND ("aElement" (DB 2)) ("aElement" (DB 1))) ("aElement" (DB 0)))
     (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 1))
          ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))))
    (IMPLIES
     (INDUCTIONHYPOTHESIS TAG
      (FORALL (DB 0)
       (FORALL (DB 0)
        (FORALL (DB 0)
         (IMPLIES
          (AND
           (AND (AND ("aElement" (DB 2)) ("aElement" (DB 1)))
                ("aElement" (DB 0)))
           (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 1))
                ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))))
          (IMPLIES ("iLess" (DB 2) (DB 5))
           (EXISTS (DB 0)
            (AND ("aElement" (DB 0))
                 (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))
                      ("sdtmndtasgtdt" (DB 1) "xR" (DB 0)))))))))))
     (EXISTS (DB 0)
      (AND ("aElement" (DB 0))
           (AND ("sdtmndtasgtdt" (DB 2) "xR" (DB 0))
                ("sdtmndtasgtdt" (DB 1) "xR" (DB 0))))))))))
(AND (AND ("aElement" "xa") ("aElement" "xb")) ("aElement" "xc"))
(AND ("sdtmndtplgtdt" "xa" "xR" "xb") ("sdtmndtplgtdt" "xa" "xR" "xc"))
(AND ("aElement" "xu")
     (AND ("aReductOfIn" "xu" "xa" "xR") ("sdtmndtasgtdt" "xu" "xR" "xb")))
(AND ("aElement" "xv")
     (AND ("aReductOfIn" "xv" "xa" "xR") ("sdtmndtasgtdt" "xv" "xR" "xc")))
(AND ("aElement" "xw")
     (AND ("sdtmndtasgtdt" "xu" "xR" "xw") ("sdtmndtasgtdt" "xv" "xR" "xw")))
("aNormalFormOfIn" "xd" "xw" "xR")
("sdtmndtasgtdt" "xb" "xR" "xd")
(AND ("aElement" "xx")
     (AND ("sdtmndtasgtdt" "xb" "xR" "xx") ("sdtmndtasgtdt" "xd" "xR" "xx")))
("sdtmndtasgtdt" "xc" "xR" "xd")
(AND ("aElement" "xy")
     (AND ("sdtmndtasgtdt" "xc" "xR" "xy") ("sdtmndtasgtdt" "xd" "xR" "xy")))
