(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aRationalNumber" (DB 0))) TRUTH))
(AND ("aRationalNumber" "xr") ("aRationalNumber" "xq"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sdtasdt" "xr" "xq")))
  ("aRationalNumber" (DB 0))))
(AND ("aRationalNumber" "xr") ("aRationalNumber" "xq"))
("=" ("sdtasdt" "xr" "xq") ("sdtasdt" "xq" "xr"))
(AND (AND ("aRationalNumber" "xr") ("aRationalNumber" "xq"))
     ("aRationalNumber" "xs"))
("=" ("sdtasdt" "xr" ("sdtasdt" "xq" "xs"))
 ("sdtasdt" ("sdtasdt" "xr" "xq") "xs"))
(AND (AND ("aRationalNumber" "xq") ("aRationalNumber" "xs"))
     ("aRationalNumber" "xr"))
(IMPLIES ("=" ("sdtasdt" "xq" "xs") ("sdtasdt" "xq" "xr")) ("=" "xs" "xr"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("aNaturalNumber" (DB 0))) ("aRationalNumber" (DB 0))))
(AND ("aNaturalNumber" "xn") ("aNaturalNumber" "xm"))
("aNaturalNumber" ("sdtasdt" "xn" "xm"))
(AND ("aNaturalNumber" "xn") ("aNaturalNumber" "xm"))
(IFF (HEADTERM TAG ("sdtbrdt" "xn" "xm"))
 (EXISTS (DB 0)
  (AND ("aNaturalNumber" (DB 0)) ("=" ("sdtasdt" (DB 0) "xn") "xm"))))
(AND ("aNaturalNumber" "xn") ("aNaturalNumber" "xm"))
(IFF (HEADTERM TAG ("misCoprime" "xn" "xm"))
 (NOT
  (EXISTS (DB 0)
   (AND ("aNaturalNumber" (DB 0))
        (AND ("sdtbrdt" (DB 0) "xn") ("sdtbrdt" (DB 0) "xm"))))))
("aNaturalNumber" "xn")
(IMPLIES (HEADTERM TAG ("isPrime" "xn")) TRUTH)
(AND
 (AND (AND ("aNaturalNumber" "xp") ("isPrime" "xp")) ("aNaturalNumber" "xn"))
 ("aNaturalNumber" "xm"))
(IMPLIES ("sdtbrdt" "xp" ("sdtasdt" "xn" "xm"))
 (OR ("sdtbrdt" "xp" "xn") ("sdtbrdt" "xp" "xm")))
("aRationalNumber" "xq")
(EXISTS (DB 0)
 (EXISTS (DB 0)
  (AND (AND ("aNaturalNumber" (DB 1)) ("aNaturalNumber" (DB 0)))
       (AND ("misCoprime" (DB 1) (DB 0))
            ("=" ("sdtasdt" (DB 1) "xq") (DB 0))))))
(AND ("aNaturalNumber" "xp") ("isPrime" "xp"))
(FORALL (DB 0)
 (IMPLIES ("aRationalNumber" (DB 0))
  (NOT ("=" "xp" ("sdtasdt" (DB 0) (DB 0))))))
(NOT ("#TH#"))
(AND ("aRationalNumber" "xq") ("=" "xp" ("sdtasdt" "xq" "xq")))
(AND (AND ("aNaturalNumber" "xm") ("aNaturalNumber" "xn"))
     (AND ("misCoprime" "xm" "xn") ("=" ("sdtasdt" "xm" "xq") "xn")))
("=" ("sdtasdt" "xp" ("sdtasdt" "xm" "xm")) ("sdtasdt" "xn" "xn"))
("sdtbrdt" "xp" "xn")
(AND ("aNaturalNumber" "xk") ("=" "xn" ("sdtasdt" "xk" "xp")))
("=" ("sdtasdt" "xp" ("sdtasdt" "xm" "xm"))
 ("sdtasdt" "xp" ("sdtasdt" "xk" "xn")))
("=" ("sdtasdt" "xm" "xm") ("sdtasdt" "xp" ("sdtasdt" "xk" "xk")))
("sdtbrdt" "xp" "xm")
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aRationalNumber" (DB 0))) TRUTH))
(AND ("aRationalNumber" "xr") ("aRationalNumber" "xq"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("sdtasdt" "xr" "xq")))
  ("aRationalNumber" (DB 0))))
(AND ("aRationalNumber" "xr") ("aRationalNumber" "xq"))
("=" ("sdtasdt" "xr" "xq") ("sdtasdt" "xq" "xr"))
(AND (AND ("aRationalNumber" "xr") ("aRationalNumber" "xq"))
     ("aRationalNumber" "xs"))
("=" ("sdtasdt" "xr" ("sdtasdt" "xq" "xs"))
 ("sdtasdt" ("sdtasdt" "xr" "xq") "xs"))
(AND (AND ("aRationalNumber" "xq") ("aRationalNumber" "xs"))
     ("aRationalNumber" "xr"))
(IMPLIES ("=" ("sdtasdt" "xq" "xs") ("sdtasdt" "xq" "xr")) ("=" "xs" "xr"))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("aNaturalNumber" (DB 0))) ("aRationalNumber" (DB 0))))
(AND ("aNaturalNumber" "xn") ("aNaturalNumber" "xm"))
("aNaturalNumber" ("sdtasdt" "xn" "xm"))
(AND ("aNaturalNumber" "xn") ("aNaturalNumber" "xm"))
(IFF (HEADTERM TAG ("sdtbrdt" "xn" "xm"))
 (EXISTS (DB 0)
  (AND ("aNaturalNumber" (DB 0)) ("=" ("sdtasdt" (DB 0) "xn") "xm"))))
(AND ("aNaturalNumber" "xn") ("aNaturalNumber" "xm"))
(IFF (HEADTERM TAG ("misCoprime" "xn" "xm"))
 (NOT
  (EXISTS (DB 0)
   (AND ("aNaturalNumber" (DB 0))
        (AND ("sdtbrdt" (DB 0) "xn") ("sdtbrdt" (DB 0) "xm"))))))
("aNaturalNumber" "xn")
(IMPLIES (HEADTERM TAG ("isPrime" "xn")) TRUTH)
(AND
 (AND (AND ("aNaturalNumber" "xp") ("isPrime" "xp")) ("aNaturalNumber" "xn"))
 ("aNaturalNumber" "xm"))
(IMPLIES ("sdtbrdt" "xp" ("sdtasdt" "xn" "xm"))
 (OR ("sdtbrdt" "xp" "xn") ("sdtbrdt" "xp" "xm")))
("aRationalNumber" "xq")
(EXISTS (DB 0)
 (EXISTS (DB 0)
  (AND (AND ("aNaturalNumber" (DB 1)) ("aNaturalNumber" (DB 0)))
       (AND ("misCoprime" (DB 1) (DB 0))
            ("=" ("sdtasdt" (DB 1) "xq") (DB 0))))))
(AND ("aNaturalNumber" "xp") ("isPrime" "xp"))
(FORALL (DB 0)
 (IMPLIES ("aRationalNumber" (DB 0))
  (NOT ("=" "xp" ("sdtasdt" (DB 0) (DB 0))))))
(NOT ("#TH#"))
(AND ("aRationalNumber" "xq") ("=" "xp" ("sdtasdt" "xq" "xq")))
(AND (AND ("aNaturalNumber" "xm") ("aNaturalNumber" "xn"))
     (AND ("misCoprime" "xm" "xn") ("=" ("sdtasdt" "xm" "xq") "xn")))
("=" ("sdtasdt" "xp" ("sdtasdt" "xm" "xm")) ("sdtasdt" "xn" "xn"))
("sdtbrdt" "xp" "xn")
(AND ("aNaturalNumber" "xk") ("=" "xn" ("sdtasdt" "xk" "xp")))
("=" ("sdtasdt" "xp" ("sdtasdt" "xm" "xm"))
 ("sdtasdt" "xp" ("sdtasdt" "xk" "xn")))
("=" ("sdtasdt" "xm" "xm") ("sdtasdt" "xp" ("sdtasdt" "xk" "xk")))
("sdtbrdt" "xp" "xm")
