(FORALL (DB 0)
 (FORALL (DB 0)
  (FORALL (DB 0)
   (FORALL (DB 0)
    (IMPLIES (AND (AND (AND TRUTHTRUTH) TRUTH) TRUTH)
     (IMPLIES ("=" ("slpdtcmdtrp" (DB 3) (DB 2)) ("slpdtcmdtrp" (DB 1) (DB 0)))
      (AND ("=" (DB 3) (DB 1)) ("=" (DB 2) (DB 0)))))))))
(AND ("aSet" "xM") ("aSet" "xN"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("szPzrzozdlpdtcmdtrp" "xM" "xN")))
  (AND ("aSet" (DB 0))
       ("=" (DB 0)
        (LAMBDA (DB 0)
          (REPLACEMENT TAG
           (EXISTS (DB 0)
            (EXISTS (DB 0)
             (AND (AND ("aElementOf" (DB 1) "xM") ("aElementOf" (DB 0) "xN"))
                  ("=" (DB 2) ("slpdtcmdtrp" (DB 1) (DB 0))))))))))))
(AND TRUTHTRUTH)
(AND ("aSet" "xM") ("aSet" "xN"))
(IMPLIES
 ("aElementOf" ("slpdtcmdtrp" "xx" "xy") ("szPzrzozdlpdtcmdtrp" "xM" "xN"))
 (AND ("aElementOf" "xx" "xM") ("aElementOf" "xy" "xN")))
("aSet" "xM")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aSubsetOf" (DB 0) "xM"))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElementOf" (DB 0) (DB 1)) ("aElementOf" (DB 0) "xM"))))))
("aFunction" "xf")
("aSubsetOf" "xM" ("szDzozmlpdtrp" "xf"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtcflbdtrb" "xf" "xM")))
  (AND ("aSet" (DB 0))
       ("=" (DB 0)
        (LAMBDA (DB 0)
          (REPLACEMENT TAG
           (EXISTS (DB 0)
            (AND ("aElementOf" (DB 0) "xM")
                 ("=" (DB 1) ("sdtlbdtrb" "xf" (DB 0)))))))))))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aOrdinal" (DB 0))) ("aSet" (DB 0))))
("aOrdinal" "xalpha")
(FORALL (DB 0) (IMPLIES ("aElementOf" (DB 0) "xalpha") ("aOrdinal" (DB 0))))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("aCardinal" (DB 0))) ("aOrdinal" (DB 0))))
(AND ("aOrdinal" "xalpha") ("aOrdinal" "xbeta"))
(IMPLIES (HEADTERM TAG ("sdtlsdt" "xalpha" "xbeta")) TRUTH)
(AND ("aOrdinal" "xalpha") ("aOrdinal" "xbeta"))
(IMPLIES ("sdtlsdt" "xalpha" "xbeta") ("aElementOf" "xalpha" "xbeta"))
("aCardinal" "xA")
("aSubsetOf" "xM" "xA")
(IFF (HEADTERM TAG ("isCofinalIn" "xM" "xA"))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) "xA")
   (EXISTS (DB 0) (AND ("aElementOf" (DB 0) "xM") ("sdtlsdt" (DB 1) (DB 0)))))))
("aSet" "xM")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("ttheCardinalityOf" "xM")))
  ("aCardinal" (DB 0))))
("aSet" "xM")
(EXISTS (DB 0) ("aElementOf" (DB 0) "xM"))
("aSet" "xN")
(IFF
 (OR ("=" ("ttheCardinalityOf" "xM") ("ttheCardinalityOf" "xN"))
     ("sdtlsdt" ("ttheCardinalityOf" "xM") ("ttheCardinalityOf" "xN")))
 (EXISTS (DB 0)
  (AND ("aFunction" (DB 0))
       (AND ("=" ("szDzozmlpdtrp" (DB 0)) "xN")
            ("=" ("sdtcflbdtrb" (DB 0) "xN") "xM")))))
("aCardinal" "xA")
("aElementOf" "xM" "xA")
("aElementOf" "xN" "xM")
("aElementOf" "xN" "xA")
("aSet" "xM")
("=" ("ttheCardinalityOf" ("szPzrzozdlpdtcmdtrp" "xM" "xM"))
 ("ttheCardinalityOf" "xM"))
("aCardinal" "xA")
("=" ("ttheCardinalityOf" "xA") "xA")
("aSet" "xM")
("aSubsetOf" "xN" "xM")
(OR ("=" ("ttheCardinalityOf" "xN") ("ttheCardinalityOf" "xM"))
    ("sdtlsdt" ("ttheCardinalityOf" "xN") ("ttheCardinalityOf" "xM")))
("aCardinal" "xA")
(IFF (HEADTERM TAG ("isRegular" "xA"))
 (FORALL (DB 0)
  (IMPLIES (AND ("aSubsetOf" (DB 0) "xA") ("isCofinalIn" (DB 0) "xA"))
   ("=" ("ttheCardinalityOf" (DB 0)) "xA"))))
("aCardinal" "xA")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("szSzuzczclpdtrp" "xA")))
  ("aCardinal" (DB 0))))
(AND ("aOrdinal" "xalpha") ("aOrdinal" "xbeta"))
(OR (OR ("sdtlsdt" "xalpha" "xbeta") ("sdtlsdt" "xbeta" "xalpha"))
    ("=" "xbeta" "xalpha"))
("aCardinal" "xA")
("sdtlsdt" "xA" ("szSzuzczclpdtrp" "xA"))
("aCardinal" "xA")
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) ("szSzuzczclpdtrp" "xA"))
  (OR ("=" ("ttheCardinalityOf" (DB 0)) "xA")
      ("sdtlsdt" ("ttheCardinalityOf" (DB 0)) "xA"))))
(FORALL (DB 0)
 (FORALL (DB 0)
  (IMPLIES (AND ("aCardinal" (DB 1)) ("aCardinal" (DB 0)))
   (NOT (AND ("sdtlsdt" (DB 1) (DB 0)) ("sdtlsdt" (DB 0) (DB 1)))))))
("aCardinal" "xA")
(NOT
 (EXISTS (DB 0)
  (AND ("aCardinal" (DB 0))
       (AND ("sdtlsdt" "xA" (DB 0))
            ("sdtlsdt" (DB 0) ("szSzuzczclpdtrp" "xA"))))))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("ttheEmptySet")))
  (AND ("aCardinal" (DB 0))
       (FORALL (DB 0)
        (IMPLIES
         (AND ("aOrdinal" (DB 0)) (EXISTS (DB 0) ("aElementOf" (DB 0) (DB 1))))
         ("aElementOf" (DB 1) (DB 0)))))))
("aSet" "xM")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("ttheConstantZeroOn" "xM")))
  (AND ("aFunction" (DB 0))
       (AND ("=" ("szDzozmlpdtrp" (DB 0)) "xM")
            (FORALL (DB 0)
             (IMPLIES ("aElementOf" (DB 0) "xM")
              ("=" ("sdtlbdtrb" (DB 1) (DB 0)) ("ttheEmptySet"))))))))
("aCardinal" "xA")
("isRegular" ("szSzuzczclpdtrp" "xA"))
(NOT ("#TH#"))
(AND
 (AND ("aSubsetOf" "xx" ("szSzuzczclpdtrp" "xA"))
      ("isCofinalIn" "xx" ("szSzuzczclpdtrp" "xA")))
 (NOT ("=" ("ttheCardinalityOf" "xx") ("szSzuzczclpdtrp" "xA"))))
(OR ("=" ("ttheCardinalityOf" "xx") "xA")
    ("sdtlsdt" ("ttheCardinalityOf" "xx") "xA"))
(AND ("aFunction" "xf")
     (AND ("=" ("szDzozmlpdtrp" "xf") "xA")
          ("=" ("sdtcflbdtrb" "xf" "xA") "xx")))
(AND (EXISTS (DB 0) ("aElementOf" (DB 0) "xx"))
     ("=" ("ttheCardinalityOf" "xA") "xA"))
(AND
 (AND ("aFunction" "xg")
      (DOMAIN TAG ("=" ("szDzozmlpdtrp" "xg") ("szSzuzczclpdtrp" "xA"))))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xg"))
   (AND
    (CONDITION TAG
     (IMPLIES (EXISTS (DB 0) ("aElementOf" (DB 0) (DB 1)))
      (EXISTS (DB 0)
       (AND
        (AND ("aFunction" (DB 0))
             (AND ("=" ("szDzozmlpdtrp" (DB 0)) "xA")
                  ("=" ("sdtcflbdtrb" (DB 0) "xA") (DB 1))))
        (EVALUATION TAG ("=" ("sdtlbdtrb" "xg" (DB 1)) (DB 0)))))))
    (CONDITION TAG
     (IMPLIES (NOT (EXISTS (DB 0) ("aElementOf" (DB 0) (DB 1))))
      (EVALUATION TAG
       ("=" ("sdtlbdtrb" "xg" (DB 0)) ("ttheConstantZeroOn" "xA")))))))))
(AND
 (AND ("aFunction" "xh")
      (DOMAIN TAG
       ("=" ("szDzozmlpdtrp" "xh") ("szPzrzozdlpdtcmdtrp" "xA" "xA"))))
 (FORALL (DB 0)
  (FORALL (DB 0)
   (IMPLIES ("aElementOf" ("slpdtcmdtrp" (DB 1) (DB 0)) ("szDzozmlpdtrp" "xh"))
    (EVALUATION TAG
     ("=" ("sdtlbdtrb" "xh" ("slpdtcmdtrp" (DB 1) (DB 0)))
      ("sdtlbdtrb" ("sdtlbdtrb" "xg" ("sdtlbdtrb" "xf" (DB 1))) (DB 0))))))))
(AND ("=" ("szDzozmlpdtrp" "xh") ("szPzrzozdlpdtcmdtrp" "xA" "xA"))
     ("=" ("sdtcflbdtrb" "xh" ("szPzrzozdlpdtcmdtrp" "xA" "xA"))
      ("szSzuzczclpdtrp" "xA")))
("=" ("szDzozmlpdtrp" "xh") ("szPzrzozdlpdtcmdtrp" "xA" "xA"))
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) ("szSzuzczclpdtrp" "xA"))
  ("aElementOf" (DB 0) ("sdtcflbdtrb" "xh" ("szPzrzozdlpdtcmdtrp" "xA" "xA")))))
("aElementOf" "xn" ("szSzuzczclpdtrp" "xA"))
(AND ("aElementOf" "xxi" "xA") ("sdtlsdt" "xn" ("sdtlbdtrb" "xf" "xxi")))
(AND ("aElementOf" "xzeta" "xA")
     ("=" ("sdtlbdtrb" ("sdtlbdtrb" "xg" ("sdtlbdtrb" "xf" "xxi")) "xzeta")
      "xn"))
("=" "xn" ("sdtlbdtrb" "xh" ("slpdtcmdtrp" "xxi" "xzeta")))
("#TH#")
("aElementOf" ("slpdtcmdtrp" "xxi" "xzeta") ("szPzrzozdlpdtcmdtrp" "xA" "xA"))
(FORALL (DB 0)
 (IMPLIES
  ("aElementOf" (DB 0) ("sdtcflbdtrb" "xh" ("szPzrzozdlpdtcmdtrp" "xA" "xA")))
  ("aElementOf" (DB 0) ("szSzuzczclpdtrp" "xA"))))
("aElementOf" "xn" ("sdtcflbdtrb" "xh" ("szPzrzozdlpdtcmdtrp" "xA" "xA")))
(AND (AND ("aElementOf" "xa" "xA") ("aElementOf" "xb" "xA"))
     ("=" "xn" ("sdtlbdtrb" "xh" ("slpdtcmdtrp" "xa" "xb"))))
(IMPLIES
 (CASEHYPOTHESIS TAG
  (EXISTS (DB 0) ("aElementOf" (DB 0) ("sdtlbdtrb" "xf" "xa"))))
 ("#TH#"))
(IMPLIES
 (CASEHYPOTHESIS TAG
  (NOT (EXISTS (DB 0) ("aElementOf" (DB 0) ("sdtlbdtrb" "xf" "xa")))))
 ("#TH#"))
(OR ("=" ("szSzuzczclpdtrp" "xA") "xA")
    ("sdtlsdt" ("szSzuzczclpdtrp" "xA") "xA"))
(FORALL (DB 0)
 (FORALL (DB 0)
  (FORALL (DB 0)
   (FORALL (DB 0)
    (IMPLIES (AND (AND (AND TRUTHTRUTH) TRUTH) TRUTH)
     (IMPLIES ("=" ("slpdtcmdtrp" (DB 3) (DB 2)) ("slpdtcmdtrp" (DB 1) (DB 0)))
      (AND ("=" (DB 3) (DB 1)) ("=" (DB 2) (DB 0)))))))))
(AND ("aSet" "xM") ("aSet" "xN"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("szPzrzozdlpdtcmdtrp" "xM" "xN")))
  (AND ("aSet" (DB 0))
       ("=" (DB 0)
        (LAMBDA (DB 0)
          (REPLACEMENT TAG
           (EXISTS (DB 0)
            (EXISTS (DB 0)
             (AND (AND ("aElementOf" (DB 1) "xM") ("aElementOf" (DB 0) "xN"))
                  ("=" (DB 2) ("slpdtcmdtrp" (DB 1) (DB 0))))))))))))
(AND TRUTHTRUTH)
(AND ("aSet" "xM") ("aSet" "xN"))
(IMPLIES
 ("aElementOf" ("slpdtcmdtrp" "xx" "xy") ("szPzrzozdlpdtcmdtrp" "xM" "xN"))
 (AND ("aElementOf" "xx" "xM") ("aElementOf" "xy" "xN")))
("aSet" "xM")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("aSubsetOf" (DB 0) "xM"))
  (AND ("aSet" (DB 0))
       (FORALL (DB 0)
        (IMPLIES ("aElementOf" (DB 0) (DB 1)) ("aElementOf" (DB 0) "xM"))))))
("aFunction" "xf")
("aSubsetOf" "xM" ("szDzozmlpdtrp" "xf"))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("sdtcflbdtrb" "xf" "xM")))
  (AND ("aSet" (DB 0))
       ("=" (DB 0)
        (LAMBDA (DB 0)
          (REPLACEMENT TAG
           (EXISTS (DB 0)
            (AND ("aElementOf" (DB 0) "xM")
                 ("=" (DB 1) ("sdtlbdtrb" "xf" (DB 0)))))))))))
(FORALL (DB 0) (IMPLIES (HEADTERM TAG ("aOrdinal" (DB 0))) ("aSet" (DB 0))))
("aOrdinal" "xalpha")
(FORALL (DB 0) (IMPLIES ("aElementOf" (DB 0) "xalpha") ("aOrdinal" (DB 0))))
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("aCardinal" (DB 0))) ("aOrdinal" (DB 0))))
(AND ("aOrdinal" "xalpha") ("aOrdinal" "xbeta"))
(IMPLIES (HEADTERM TAG ("sdtlsdt" "xalpha" "xbeta")) TRUTH)
(AND ("aOrdinal" "xalpha") ("aOrdinal" "xbeta"))
(IMPLIES ("sdtlsdt" "xalpha" "xbeta") ("aElementOf" "xalpha" "xbeta"))
("aCardinal" "xA")
("aSubsetOf" "xM" "xA")
(IFF (HEADTERM TAG ("isCofinalIn" "xM" "xA"))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) "xA")
   (EXISTS (DB 0) (AND ("aElementOf" (DB 0) "xM") ("sdtlsdt" (DB 1) (DB 0)))))))
("aSet" "xM")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("ttheCardinalityOf" "xM")))
  ("aCardinal" (DB 0))))
("aSet" "xM")
(EXISTS (DB 0) ("aElementOf" (DB 0) "xM"))
("aSet" "xN")
(IFF
 (OR ("=" ("ttheCardinalityOf" "xM") ("ttheCardinalityOf" "xN"))
     ("sdtlsdt" ("ttheCardinalityOf" "xM") ("ttheCardinalityOf" "xN")))
 (EXISTS (DB 0)
  (AND ("aFunction" (DB 0))
       (AND ("=" ("szDzozmlpdtrp" (DB 0)) "xN")
            ("=" ("sdtcflbdtrb" (DB 0) "xN") "xM")))))
("aCardinal" "xA")
("aElementOf" "xM" "xA")
("aElementOf" "xN" "xM")
("aElementOf" "xN" "xA")
("aSet" "xM")
("=" ("ttheCardinalityOf" ("szPzrzozdlpdtcmdtrp" "xM" "xM"))
 ("ttheCardinalityOf" "xM"))
("aCardinal" "xA")
("=" ("ttheCardinalityOf" "xA") "xA")
("aSet" "xM")
("aSubsetOf" "xN" "xM")
(OR ("=" ("ttheCardinalityOf" "xN") ("ttheCardinalityOf" "xM"))
    ("sdtlsdt" ("ttheCardinalityOf" "xN") ("ttheCardinalityOf" "xM")))
("aCardinal" "xA")
(IFF (HEADTERM TAG ("isRegular" "xA"))
 (FORALL (DB 0)
  (IMPLIES (AND ("aSubsetOf" (DB 0) "xA") ("isCofinalIn" (DB 0) "xA"))
   ("=" ("ttheCardinalityOf" (DB 0)) "xA"))))
("aCardinal" "xA")
(FORALL (DB 0)
 (IMPLIES (HEADTERM TAG ("=" (DB 0) ("szSzuzczclpdtrp" "xA")))
  ("aCardinal" (DB 0))))
(AND ("aOrdinal" "xalpha") ("aOrdinal" "xbeta"))
(OR (OR ("sdtlsdt" "xalpha" "xbeta") ("sdtlsdt" "xbeta" "xalpha"))
    ("=" "xbeta" "xalpha"))
("aCardinal" "xA")
("sdtlsdt" "xA" ("szSzuzczclpdtrp" "xA"))
("aCardinal" "xA")
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) ("szSzuzczclpdtrp" "xA"))
  (OR ("=" ("ttheCardinalityOf" (DB 0)) "xA")
      ("sdtlsdt" ("ttheCardinalityOf" (DB 0)) "xA"))))
(FORALL (DB 0)
 (FORALL (DB 0)
  (IMPLIES (AND ("aCardinal" (DB 1)) ("aCardinal" (DB 0)))
   (NOT (AND ("sdtlsdt" (DB 1) (DB 0)) ("sdtlsdt" (DB 0) (DB 1)))))))
("aCardinal" "xA")
(NOT
 (EXISTS (DB 0)
  (AND ("aCardinal" (DB 0))
       (AND ("sdtlsdt" "xA" (DB 0))
            ("sdtlsdt" (DB 0) ("szSzuzczclpdtrp" "xA"))))))
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("ttheEmptySet")))
  (AND ("aCardinal" (DB 0))
       (FORALL (DB 0)
        (IMPLIES
         (AND ("aOrdinal" (DB 0)) (EXISTS (DB 0) ("aElementOf" (DB 0) (DB 1))))
         ("aElementOf" (DB 1) (DB 0)))))))
("aSet" "xM")
(FORALL (DB 0)
 (IFF (HEADTERM TAG ("=" (DB 0) ("ttheConstantZeroOn" "xM")))
  (AND ("aFunction" (DB 0))
       (AND ("=" ("szDzozmlpdtrp" (DB 0)) "xM")
            (FORALL (DB 0)
             (IMPLIES ("aElementOf" (DB 0) "xM")
              ("=" ("sdtlbdtrb" (DB 1) (DB 0)) ("ttheEmptySet"))))))))
("aCardinal" "xA")
("isRegular" ("szSzuzczclpdtrp" "xA"))
(NOT ("#TH#"))
(AND
 (AND ("aSubsetOf" "xx" ("szSzuzczclpdtrp" "xA"))
      ("isCofinalIn" "xx" ("szSzuzczclpdtrp" "xA")))
 (NOT ("=" ("ttheCardinalityOf" "xx") ("szSzuzczclpdtrp" "xA"))))
(OR ("=" ("ttheCardinalityOf" "xx") "xA")
    ("sdtlsdt" ("ttheCardinalityOf" "xx") "xA"))
(AND ("aFunction" "xf")
     (AND ("=" ("szDzozmlpdtrp" "xf") "xA")
          ("=" ("sdtcflbdtrb" "xf" "xA") "xx")))
(AND (EXISTS (DB 0) ("aElementOf" (DB 0) "xx"))
     ("=" ("ttheCardinalityOf" "xA") "xA"))
(AND
 (AND ("aFunction" "xg")
      (DOMAIN TAG ("=" ("szDzozmlpdtrp" "xg") ("szSzuzczclpdtrp" "xA"))))
 (FORALL (DB 0)
  (IMPLIES ("aElementOf" (DB 0) ("szDzozmlpdtrp" "xg"))
   (AND
    (CONDITION TAG
     (IMPLIES (EXISTS (DB 0) ("aElementOf" (DB 0) (DB 1)))
      (EXISTS (DB 0)
       (AND
        (AND ("aFunction" (DB 0))
             (AND ("=" ("szDzozmlpdtrp" (DB 0)) "xA")
                  ("=" ("sdtcflbdtrb" (DB 0) "xA") (DB 1))))
        (EVALUATION TAG ("=" ("sdtlbdtrb" "xg" (DB 1)) (DB 0)))))))
    (CONDITION TAG
     (IMPLIES (NOT (EXISTS (DB 0) ("aElementOf" (DB 0) (DB 1))))
      (EVALUATION TAG
       ("=" ("sdtlbdtrb" "xg" (DB 0)) ("ttheConstantZeroOn" "xA")))))))))
(AND
 (AND ("aFunction" "xh")
      (DOMAIN TAG
       ("=" ("szDzozmlpdtrp" "xh") ("szPzrzozdlpdtcmdtrp" "xA" "xA"))))
 (FORALL (DB 0)
  (FORALL (DB 0)
   (IMPLIES ("aElementOf" ("slpdtcmdtrp" (DB 1) (DB 0)) ("szDzozmlpdtrp" "xh"))
    (EVALUATION TAG
     ("=" ("sdtlbdtrb" "xh" ("slpdtcmdtrp" (DB 1) (DB 0)))
      ("sdtlbdtrb" ("sdtlbdtrb" "xg" ("sdtlbdtrb" "xf" (DB 1))) (DB 0))))))))
(AND ("=" ("szDzozmlpdtrp" "xh") ("szPzrzozdlpdtcmdtrp" "xA" "xA"))
     ("=" ("sdtcflbdtrb" "xh" ("szPzrzozdlpdtcmdtrp" "xA" "xA"))
      ("szSzuzczclpdtrp" "xA")))
("=" ("szDzozmlpdtrp" "xh") ("szPzrzozdlpdtcmdtrp" "xA" "xA"))
(FORALL (DB 0)
 (IMPLIES ("aElementOf" (DB 0) ("szSzuzczclpdtrp" "xA"))
  ("aElementOf" (DB 0) ("sdtcflbdtrb" "xh" ("szPzrzozdlpdtcmdtrp" "xA" "xA")))))
("aElementOf" "xn" ("szSzuzczclpdtrp" "xA"))
(AND ("aElementOf" "xxi" "xA") ("sdtlsdt" "xn" ("sdtlbdtrb" "xf" "xxi")))
(AND ("aElementOf" "xzeta" "xA")
     ("=" ("sdtlbdtrb" ("sdtlbdtrb" "xg" ("sdtlbdtrb" "xf" "xxi")) "xzeta")
      "xn"))
("=" "xn" ("sdtlbdtrb" "xh" ("slpdtcmdtrp" "xxi" "xzeta")))
("#TH#")
("aElementOf" ("slpdtcmdtrp" "xxi" "xzeta") ("szPzrzozdlpdtcmdtrp" "xA" "xA"))
(FORALL (DB 0)
 (IMPLIES
  ("aElementOf" (DB 0) ("sdtcflbdtrb" "xh" ("szPzrzozdlpdtcmdtrp" "xA" "xA")))
  ("aElementOf" (DB 0) ("szSzuzczclpdtrp" "xA"))))
("aElementOf" "xn" ("sdtcflbdtrb" "xh" ("szPzrzozdlpdtcmdtrp" "xA" "xA")))
(AND (AND ("aElementOf" "xa" "xA") ("aElementOf" "xb" "xA"))
     ("=" "xn" ("sdtlbdtrb" "xh" ("slpdtcmdtrp" "xa" "xb"))))
(IMPLIES
 (CASEHYPOTHESIS TAG
  (EXISTS (DB 0) ("aElementOf" (DB 0) ("sdtlbdtrb" "xf" "xa"))))
 ("#TH#"))
(IMPLIES
 (CASEHYPOTHESIS TAG
  (NOT (EXISTS (DB 0) ("aElementOf" (DB 0) ("sdtlbdtrb" "xf" "xa")))))
 ("#TH#"))
(OR ("=" ("szSzuzczclpdtrp" "xA") "xA")
    ("sdtlsdt" ("szSzuzczclpdtrp" "xA") "xA"))
